//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.18 at 10:09:02 AM CST 
//


package com.zebone.nhis.ma.pub.platform.send.impl.yh.vo.DeptChange;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PATIENT_ID"/>
 *         &lt;element ref="{}ADMISS_TIMES"/>
 *         &lt;element ref="{}TRAN_DATE"/>
 *         &lt;element ref="{}ORIG_DEPT"/>
 *         &lt;element ref="{}ORIG_WARD"/>
 *         &lt;element ref="{}ORIG_BED"/>
 *         &lt;element ref="{}CURR_DEPT"/>
 *         &lt;element ref="{}CURR_WARD"/>
 *         &lt;element ref="{}CURR_BED"/>
 *         &lt;element ref="{}CURR_OPERA"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientid",
    "admisstimes",
    "trandate",
    "origdept",
    "origward",
    "origbed",
    "currdept",
    "currward",
    "currbed",
    "curropera"
})
@XmlRootElement(name = "Msg")
public class DeptChangeInfo {

    @XmlElement(name = "PATIENT_ID", required = true)
    protected String patientid;
    @XmlElement(name = "ADMISS_TIMES", required = true)
    protected String admisstimes;
    @XmlElement(name = "TRAN_DATE", required = true)
    protected String trandate;
    @XmlElement(name = "ORIG_DEPT", required = true)
    protected String origdept;
    @XmlElement(name = "ORIG_WARD", required = true)
    protected String origward;
    @XmlElement(name = "ORIG_BED", required = true)
    protected String origbed;
    @XmlElement(name = "CURR_DEPT", required = true)
    protected String currdept;
    @XmlElement(name = "CURR_WARD", required = true)
    protected String currward;
    @XmlElement(name = "CURR_BED", required = true)
    protected String currbed;
    @XmlElement(name = "CURR_OPERA", required = true)
    protected String curropera;
    @XmlAttribute(name = "action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String action;

    /**
     * Gets the value of the patientid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATIENTID() {
        return patientid;
    }

    /**
     * Sets the value of the patientid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATIENTID(String value) {
        this.patientid = value;
    }

    /**
     * Gets the value of the admisstimes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMISSTIMES() {
        return admisstimes;
    }

    /**
     * Sets the value of the admisstimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMISSTIMES(String value) {
        this.admisstimes = value;
    }

    /**
     * Gets the value of the trandate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANDATE() {
        return trandate;
    }

    /**
     * Sets the value of the trandate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANDATE(String value) {
        this.trandate = value;
    }

    /**
     * Gets the value of the origdept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGDEPT() {
        return origdept;
    }

    /**
     * Sets the value of the origdept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGDEPT(String value) {
        this.origdept = value;
    }

    /**
     * Gets the value of the origward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGWARD() {
        return origward;
    }

    /**
     * Sets the value of the origward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGWARD(String value) {
        this.origward = value;
    }

    /**
     * Gets the value of the origbed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGBED() {
        return origbed;
    }

    /**
     * Sets the value of the origbed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGBED(String value) {
        this.origbed = value;
    }

    /**
     * Gets the value of the currdept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRDEPT() {
        return currdept;
    }

    /**
     * Sets the value of the currdept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRDEPT(String value) {
        this.currdept = value;
    }

    /**
     * Gets the value of the currward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRWARD() {
        return currward;
    }

    /**
     * Sets the value of the currward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRWARD(String value) {
        this.currward = value;
    }

    /**
     * Gets the value of the currbed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRBED() {
        return currbed;
    }

    /**
     * Sets the value of the currbed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRBED(String value) {
        this.currbed = value;
    }

    /**
     * Gets the value of the curropera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURROPERA() {
        return curropera;
    }

    /**
     * Sets the value of the curropera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURROPERA(String value) {
        this.curropera = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
