//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.23 at 04:09:04 PM CST 
//


package com.zebone.nhis.ma.tpi.rhip.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "Ipt_PhysiqueExam")
@XmlAccessorType(XmlAccessType.FIELD)
public class IptPhysiqueExam {

	//体温（℃）
    @XmlElement(name = "TW")
    protected String tw;
	//心率（次/min）    
    @XmlElement(name = "XL")
    protected String xl;
    //呼吸频率（次/min）
    @XmlElement(name = "HXPL")
    protected String hxpl;
    //收缩压（mmHg）
    @XmlElement(name = "SSY")
    protected String ssy;
    //舒张压（mmHg）
    @XmlElement(name = "SZY")
    protected String szy;
    @XmlElement(name = "TGJC")
    protected String tgjc;
    @XmlElement(name = "Day31InpatientMk")
    protected String day31InpatientMk;
    @XmlElement(name = "Day31InpatientAim")
    protected String day31InpatientAim;
    
    
	public String getTw() {
		return tw;
	}
	public void setTw(String tw) {
		this.tw = tw;
	}
	public String getXl() {
		return xl;
	}
	public void setXl(String xl) {
		this.xl = xl;
	}
	public String getHxpl() {
		return hxpl;
	}
	public void setHxpl(String hxpl) {
		this.hxpl = hxpl;
	}
	public String getSsy() {
		return ssy;
	}
	public void setSsy(String ssy) {
		this.ssy = ssy;
	}
	public String getSzy() {
		return szy;
	}
	public void setSzy(String szy) {
		this.szy = szy;
	}
	public String getDay31InpatientMk() {
		return day31InpatientMk;
	}
	public void setDay31InpatientMk(String day31InpatientMk) {
		this.day31InpatientMk = day31InpatientMk;
	}
	public String getTgjc() {
		return tgjc;
	}
	public void setTgjc(String tgjc) {
		this.tgjc = tgjc;
	}
	public String getDay31InpatientAim() {
		return day31InpatientAim;
	}
	public void setDay31InpatientAim(String day31InpatientAim) {
		this.day31InpatientAim = day31InpatientAim;
	}

 

}
