package com.zebone.nhis.webservice.client.zhongshan.tpi.rhip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebServiceEntry", targetNamespace = "http://ws.adapter.bsoft.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceEntry {

	/**
	 * 
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String invoke(
			@WebParam(name = "arg0", partName = "arg0") String arg0,
			@WebParam(name = "arg1", partName = "arg1") String arg1,
			@WebParam(name = "arg2", partName = "arg2") String arg2,
			@WebParam(name = "arg3", partName = "arg3") String arg3,
			@WebParam(name = "arg4", partName = "arg4") StringArray arg4)
			throws Exception_Exception;

	/**
     * 
     */
	@WebMethod
	public void startWs();

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String transportData(
			@WebParam(name = "arg0", partName = "arg0") String arg0,
			@WebParam(name = "arg1", partName = "arg1") String arg1,
			@WebParam(name = "arg2", partName = "arg2") int arg2,
			@WebParam(name = "arg3", partName = "arg3") String arg3)
			throws Exception_Exception;

}
