//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.21 at 02:07:43 PM CST 
//


package com.zebone.nhis.ma.pub.platform.receive.yh.vo.StrikeSettle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PAT_INDEX_NO"/>
 *         &lt;element ref="{}MFS_TYPE_CODE"/>
 *         &lt;element ref="{}MFS_RESULT_CODE"/>
 *         &lt;element ref="{}DEPT_INDEX_NO_APP"/>
 *         &lt;element ref="{}PREPAID_MONEY"/>
 *         &lt;element ref="{}SELF_TOTAL_PAYMENT"/>
 *         &lt;element ref="{}SELF_PAYMENT_FEE"/>
 *         &lt;element ref="{}INHOSP_INDEX_NO"/>
 *         &lt;element ref="{}MFS_METHOD_CODE"/>
 *         &lt;element ref="{}RECEIPT_TYPE"/>
 *         &lt;element ref="{}RECEIPT_INDEX_NO"/>
 *         &lt;element ref="{}INVOICE_NO"/>
 *         &lt;element ref="{}SELF_INDEX_NO"/>
 *         &lt;element ref="{}MEDICARE_PAYMENT"/>
 *         &lt;element ref="{}OPERATOR_NO"/>
 *         &lt;element ref="{}OPERAT_TIME"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patindexno",
    "mfstypecode",
    "mfsresultcode",
    "deptindexnoapp",
    "prepaidmoney",
    "selftotalpayment",
    "selfpaymentfee",
    "inhospindexno",
    "mfsmethodcode",
    "receipttype",
    "receiptindexno",
    "invoiceno",
    "selfindexno",
    "medicarepayment",
    "operatorno",
    "operattime"
})
@XmlRootElement(name = "Msg")
public class StrikeSettleInfo {

    @XmlElement(name = "PAT_INDEX_NO", required = true)
    protected String patindexno;
    @XmlElement(name = "MFS_TYPE_CODE", required = true)
    protected String mfstypecode;
    @XmlElement(name = "MFS_RESULT_CODE", required = true)
    protected String mfsresultcode;
    @XmlElement(name = "DEPT_INDEX_NO_APP", required = true)
    protected String deptindexnoapp;
    @XmlElement(name = "PREPAID_MONEY", required = true)
    protected String prepaidmoney;
    @XmlElement(name = "SELF_TOTAL_PAYMENT", required = true)
    protected String selftotalpayment;
    @XmlElement(name = "SELF_PAYMENT_FEE", required = true)
    protected String selfpaymentfee;
    @XmlElement(name = "INHOSP_INDEX_NO", required = true)
    protected String inhospindexno;
    @XmlElement(name = "MFS_METHOD_CODE", required = true)
    protected String mfsmethodcode;
    @XmlElement(name = "RECEIPT_TYPE", required = true)
    protected String receipttype;
    @XmlElement(name = "RECEIPT_INDEX_NO", required = true)
    protected String receiptindexno;
    @XmlElement(name = "INVOICE_NO", required = true)
    protected String invoiceno;
    @XmlElement(name = "SELF_INDEX_NO", required = true)
    protected String selfindexno;
    @XmlElement(name = "MEDICARE_PAYMENT", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String medicarepayment;
    @XmlElement(name = "OPERATOR_NO", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String operatorno;
    @XmlElement(name = "OPERAT_TIME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String operattime;
    @XmlAttribute(name = "action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String action;

    /**
     * Gets the value of the patindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATINDEXNO() {
        return patindexno;
    }

    /**
     * Sets the value of the patindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATINDEXNO(String value) {
        this.patindexno = value;
    }

    /**
     * Gets the value of the mfstypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMFSTYPECODE() {
        return mfstypecode;
    }

    /**
     * Sets the value of the mfstypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMFSTYPECODE(String value) {
        this.mfstypecode = value;
    }

    /**
     * Gets the value of the mfsresultcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMFSRESULTCODE() {
        return mfsresultcode;
    }

    /**
     * Sets the value of the mfsresultcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMFSRESULTCODE(String value) {
        this.mfsresultcode = value;
    }

    /**
     * Gets the value of the deptindexnoapp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPTINDEXNOAPP() {
        return deptindexnoapp;
    }

    /**
     * Sets the value of the deptindexnoapp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPTINDEXNOAPP(String value) {
        this.deptindexnoapp = value;
    }

    /**
     * Gets the value of the prepaidmoney property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREPAIDMONEY() {
        return prepaidmoney;
    }

    /**
     * Sets the value of the prepaidmoney property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREPAIDMONEY(String value) {
        this.prepaidmoney = value;
    }

    /**
     * Gets the value of the selftotalpayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSELFTOTALPAYMENT() {
        return selftotalpayment;
    }

    /**
     * Sets the value of the selftotalpayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSELFTOTALPAYMENT(String value) {
        this.selftotalpayment = value;
    }

    /**
     * Gets the value of the selfpaymentfee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSELFPAYMENTFEE() {
        return selfpaymentfee;
    }

    /**
     * Sets the value of the selfpaymentfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSELFPAYMENTFEE(String value) {
        this.selfpaymentfee = value;
    }

    /**
     * Gets the value of the inhospindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINHOSPINDEXNO() {
        return inhospindexno;
    }

    /**
     * Sets the value of the inhospindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINHOSPINDEXNO(String value) {
        this.inhospindexno = value;
    }

    /**
     * Gets the value of the mfsmethodcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMFSMETHODCODE() {
        return mfsmethodcode;
    }

    /**
     * Sets the value of the mfsmethodcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMFSMETHODCODE(String value) {
        this.mfsmethodcode = value;
    }

    /**
     * Gets the value of the receipttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIPTTYPE() {
        return receipttype;
    }

    /**
     * Sets the value of the receipttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIPTTYPE(String value) {
        this.receipttype = value;
    }

    /**
     * Gets the value of the receiptindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIPTINDEXNO() {
        return receiptindexno;
    }

    /**
     * Sets the value of the receiptindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIPTINDEXNO(String value) {
        this.receiptindexno = value;
    }

    /**
     * Gets the value of the invoiceno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVOICENO() {
        return invoiceno;
    }

    /**
     * Sets the value of the invoiceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVOICENO(String value) {
        this.invoiceno = value;
    }

    /**
     * Gets the value of the selfindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSELFINDEXNO() {
        return selfindexno;
    }

    /**
     * Sets the value of the selfindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSELFINDEXNO(String value) {
        this.selfindexno = value;
    }

    /**
     * Gets the value of the medicarepayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEDICAREPAYMENT() {
        return medicarepayment;
    }

    /**
     * Sets the value of the medicarepayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEDICAREPAYMENT(String value) {
        this.medicarepayment = value;
    }

    /**
     * Gets the value of the operatorno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPERATORNO() {
        return operatorno;
    }

    /**
     * Sets the value of the operatorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPERATORNO(String value) {
        this.operatorno = value;
    }

    /**
     * Gets the value of the operattime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPERATTIME() {
        return operattime;
    }

    /**
     * Sets the value of the operattime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPERATTIME(String value) {
        this.operattime = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
