//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 05:07:21 PM CST 
//


package com.zebone.nhis.ma.pub.platform.send.impl.yh.vo.CnLabApplyAndOcc;



import com.zebone.nhis.ma.pub.platform.send.impl.yh.vo.CnLabApplyAndOccDetail.CnLabApplyAndOccDetailRow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OUTHOSP_INDEX_NO"/>
 *         &lt;element ref="{}VISIT_CARD_NO"/>
 *         &lt;element ref="{}OUTHOSP_NO"/>
 *         &lt;element ref="{}INHOSP_INDEX_NO"/>
 *         &lt;element ref="{}MR_NO"/>
 *         &lt;element ref="{}ANAMNESIS_NO"/>
 *         &lt;element ref="{}INHOSP_NUM"/>
 *         &lt;element ref="{}INHOSP_NO"/>
 *         &lt;element ref="{}PAT_INDEX_NO"/>
 *         &lt;element ref="{}ELECTR_REQUISITION_NO"/>
 *         &lt;element ref="{}ORDER_NO"/>
 *         &lt;element ref="{}ORDER_GROUP_NO"/>
 *         &lt;element ref="{}REPORT_NO"/>
 *         &lt;element ref="{}TEST_PAT_RESOURCE_CODE"/>
 *         &lt;element ref="{}TEST_PAT_RESOURCE_NAME"/>
 *         &lt;element ref="{}REPORT_NAME"/>
 *         &lt;element ref="{}APPLY_DATE"/>
 *         &lt;element ref="{}TEST_CATEG_CODE"/>
 *         &lt;element ref="{}TEST_CATEG_NAME"/>
 *         &lt;element ref="{}EXECUT_DATE"/>
 *         &lt;element ref="{}REPORT_DATE"/>
 *         &lt;element ref="{}SAMPLE_NO"/>
 *         &lt;element ref="{}MICROBE_TEST_FLAG"/>
 *         &lt;element ref="{}APPLY_DEPT_INDEX_NO"/>
 *         &lt;element ref="{}APPLY_DEPT_CODE"/>
 *         &lt;element ref="{}APPLY_DEPT_NAME"/>
 *         &lt;element ref="{}EXECUT_DEPT_INDEX_NO"/>
 *         &lt;element ref="{}EXECUT_DEPT_CODE"/>
 *         &lt;element ref="{}EXECUT_DEPT_NAME"/>
 *         &lt;element ref="{}APPLY_DR_INDEX_NO"/>
 *         &lt;element ref="{}APPLY_DR_CODE"/>
 *         &lt;element ref="{}APPLY_DR_NAME"/>
 *         &lt;element ref="{}EXECUT_DR_INDEX_NO"/>
 *         &lt;element ref="{}EXECUT_DR_CODE"/>
 *         &lt;element ref="{}EXECUT_DR_NAME"/>
 *         &lt;element ref="{}REPORT_DR_INDEX_NO"/>
 *         &lt;element ref="{}REPORT_DR_CODE"/>
 *         &lt;element ref="{}REPORT_DR_NAME"/>
 *         &lt;element ref="{}CLINIC_DIAG_CODE"/>
 *         &lt;element ref="{}CLINIC_DIAG_NAME"/>
 *         &lt;element ref="{}ID_NUMBER"/>
 *         &lt;element ref="{}PAT_NAME"/>
 *         &lt;element ref="{}PHYSI_SEX_CODE"/>
 *         &lt;element ref="{}PHYSI_SEX_NAME"/>
 *         &lt;element ref="{}DATE_BIRTH"/>
 *         &lt;element ref="{}ETHNIC_CODE"/>
 *         &lt;element ref="{}ETHNIC_NAME"/>
 *         &lt;element ref="{}MARITAL_STATUS_CODE"/>
 *         &lt;element ref="{}MARITAL_STATUS_NAME"/>
 *         &lt;element ref="{}RECORD_DATE"/>
 *         &lt;element ref="{}UPDATE_DATE"/>
 *         &lt;element ref="{}EQUIPMENT_CODE"/>
 *         &lt;element ref="{}EQUIPMENT_NAME"/>
 *         &lt;element ref="{}NOTE"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outhospindexno",
    "visitcardno",
    "outhospno",
    "inhospindexno",
    "mrno",
    "anamnesisno",
    "inhospnum",
    "inhospno",
    "patindexno",
    "electrrequisitionno",
    "orderno",
    "ordergroupno",
    "reportno",
    "testpatresourcecode",
    "testpatresourcename",
    "reportname",
    "applydate",
    "testcategcode",
    "testcategname",
    "executdate",
    "reportdate",
    "sampleno",
    "microbetestflag",
    "applydeptindexno",
    "applydeptcode",
    "applydeptname",
    "executdeptindexno",
    "executdeptcode",
    "executdeptname",
    "applydrindexno",
    "applydrcode",
    "applydrname",
    "executdrindexno",
    "executdrcode",
    "executdrname",
    "reportdrindexno",
    "reportdrcode",
    "reportdrname",
    "clinicdiagcode",
    "clinicdiagname",
    "idnumber",
    "patname",
    "physisexcode",
    "physisexname",
    "datebirth",
    "ethniccode",
    "ethnicname",
    "maritalstatuscode",
    "maritalstatusname",
    "recorddate",
    "updatedate",
    "equipmentcode",
    "equipmentname",
    "note",
        "as20004"
})
@XmlRootElement(name = "row")
/**
 * BS20003 检验报告 V3.10
 * @author gongyy
 * @date 2018-12-11 18:09:22
 */
public class CnLabApplyAndOccRow {

    @XmlElement(name = "OUTHOSP_INDEX_NO", required = true)
    private  String outhospindexno;
    @XmlElement(name = "VISIT_CARD_NO", required = true)
    private  String visitcardno;
    @XmlElement(name = "OUTHOSP_NO", required = true)
    private  String outhospno;
    @XmlElement(name = "INHOSP_INDEX_NO", required = true)
    private  String inhospindexno;
    @XmlElement(name = "MR_NO", required = true)
    private  String mrno;
    @XmlElement(name = "ANAMNESIS_NO", required = true)
    private  String anamnesisno;
    @XmlElement(name = "INHOSP_NUM", required = true)
    private  String inhospnum;
    @XmlElement(name = "INHOSP_NO", required = true)
    private  String inhospno;
    @XmlElement(name = "PAT_INDEX_NO", required = true)
    private  String patindexno;
    @XmlElement(name = "ELECTR_REQUISITION_NO", required = true)
    private  String electrrequisitionno;
    @XmlElement(name = "ORDER_NO", required = true)
    private  String orderno;
    @XmlElement(name = "ORDER_GROUP_NO", required = true)
    private  String ordergroupno;
    @XmlElement(name = "REPORT_NO", required = true)
    private  String reportno;
    @XmlElement(name = "TEST_PAT_RESOURCE_CODE", required = true)
    private  String testpatresourcecode;
    @XmlElement(name = "TEST_PAT_RESOURCE_NAME", required = true)
    private  String testpatresourcename;
    @XmlElement(name = "REPORT_NAME", required = true)
    private  String reportname;
    @XmlElement(name = "APPLY_DATE", required = true)
    private  String applydate;
    @XmlElement(name = "TEST_CATEG_CODE", required = true)
    private  String testcategcode;
    @XmlElement(name = "TEST_CATEG_NAME", required = true)
    private  String testcategname;
    @XmlElement(name = "EXECUT_DATE", required = true)
    private  String executdate;
    @XmlElement(name = "REPORT_DATE", required = true)
    private  String reportdate;
    @XmlElement(name = "SAMPLE_NO", required = true)
    private  String sampleno;
    @XmlElement(name = "MICROBE_TEST_FLAG", required = true)
    private  String microbetestflag;
    @XmlElement(name = "APPLY_DEPT_INDEX_NO", required = true)
    private  String applydeptindexno;
    @XmlElement(name = "APPLY_DEPT_CODE", required = true)
    private  String applydeptcode;
    @XmlElement(name = "APPLY_DEPT_NAME", required = true)
    private  String applydeptname;
    @XmlElement(name = "EXECUT_DEPT_INDEX_NO", required = true)
    private  String executdeptindexno;
    @XmlElement(name = "EXECUT_DEPT_CODE", required = true)
    private  String executdeptcode;
    @XmlElement(name = "EXECUT_DEPT_NAME", required = true)
    private  String executdeptname;
    @XmlElement(name = "APPLY_DR_INDEX_NO", required = true)
    private  String applydrindexno;
    @XmlElement(name = "APPLY_DR_CODE", required = true)
    private  String applydrcode;
    @XmlElement(name = "APPLY_DR_NAME", required = true)
    private  String applydrname;
    @XmlElement(name = "EXECUT_DR_INDEX_NO", required = true)
    private  String executdrindexno;
    @XmlElement(name = "EXECUT_DR_CODE", required = true)
    private  String executdrcode;
    @XmlElement(name = "EXECUT_DR_NAME", required = true)
    private  String executdrname;
    @XmlElement(name = "REPORT_DR_INDEX_NO", required = true)
    private  String reportdrindexno;
    @XmlElement(name = "REPORT_DR_CODE", required = true)
    private  String reportdrcode;
    @XmlElement(name = "REPORT_DR_NAME", required = true)
    private  String reportdrname;
    @XmlElement(name = "CLINIC_DIAG_CODE", required = true)
    private  String clinicdiagcode;
    @XmlElement(name = "CLINIC_DIAG_NAME", required = true)
    private  String clinicdiagname;
    @XmlElement(name = "ID_NUMBER", required = true)
    private  String idnumber;
    @XmlElement(name = "PAT_NAME", required = true)
    private  String patname;
    @XmlElement(name = "PHYSI_SEX_CODE", required = true)
    private  String physisexcode;
    @XmlElement(name = "PHYSI_SEX_NAME", required = true)
    private  String physisexname;
    @XmlElement(name = "DATE_BIRTH", required = true)
    private  String datebirth;
    @XmlElement(name = "ETHNIC_CODE", required = true)
    private  String ethniccode;
    @XmlElement(name = "ETHNIC_NAME", required = true)
    private  String ethnicname;
    @XmlElement(name = "MARITAL_STATUS_CODE", required = true)
    private  String maritalstatuscode;
    @XmlElement(name = "MARITAL_STATUS_NAME", required = true)
    private  String maritalstatusname;
    @XmlElement(name = "RECORD_DATE", required = true)
    private  String recorddate;
    @XmlElement(name = "UPDATE_DATE", required = true)
    private  String updatedate;
    @XmlElement(name = "EQUIPMENT_CODE", required = true)
    private  String equipmentcode;
    @XmlElement(name = "EQUIPMENT_NAME", required = true)
    private  String equipmentname;
    @XmlElement(name = "NOTE", required = true)
    private  String note;
    @XmlAttribute(name = "action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    private  String action;
    @XmlElement(name = "AS20004",required = true)
    private ArrayList<CnLabApplyAndOccDetailRow> as20004;

    public ArrayList<CnLabApplyAndOccDetailRow> getAs20004() {
        return as20004;
    }

    public void setAs20004(ArrayList<CnLabApplyAndOccDetailRow> as20004) {
        this.as20004 = as20004;
    }

    /**
     * Gets the value of the outhospindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOUTHOSPINDEXNO() {
        return outhospindexno;
    }

    /**
     * Sets the value of the outhospindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOUTHOSPINDEXNO(String value) {
        this.outhospindexno = value;
    }

    /**
     * Gets the value of the visitcardno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVISITCARDNO() {
        return visitcardno;
    }

    /**
     * Sets the value of the visitcardno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVISITCARDNO(String value) {
        this.visitcardno = value;
    }

    /**
     * Gets the value of the outhospno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOUTHOSPNO() {
        return outhospno;
    }

    /**
     * Sets the value of the outhospno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOUTHOSPNO(String value) {
        this.outhospno = value;
    }

    /**
     * Gets the value of the inhospindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINHOSPINDEXNO() {
        return inhospindexno;
    }

    /**
     * Sets the value of the inhospindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINHOSPINDEXNO(String value) {
        this.inhospindexno = value;
    }

    /**
     * Gets the value of the mrno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMRNO() {
        return mrno;
    }

    /**
     * Sets the value of the mrno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMRNO(String value) {
        this.mrno = value;
    }

    /**
     * Gets the value of the anamnesisno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANAMNESISNO() {
        return anamnesisno;
    }

    /**
     * Sets the value of the anamnesisno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANAMNESISNO(String value) {
        this.anamnesisno = value;
    }

    /**
     * Gets the value of the inhospnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINHOSPNUM() {
        return inhospnum;
    }

    /**
     * Sets the value of the inhospnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINHOSPNUM(String value) {
        this.inhospnum = value;
    }

    /**
     * Gets the value of the inhospno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINHOSPNO() {
        return inhospno;
    }

    /**
     * Sets the value of the inhospno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINHOSPNO(String value) {
        this.inhospno = value;
    }

    /**
     * Gets the value of the patindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATINDEXNO() {
        return patindexno;
    }

    /**
     * Sets the value of the patindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATINDEXNO(String value) {
        this.patindexno = value;
    }

    /**
     * Gets the value of the electrrequisitionno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getELECTRREQUISITIONNO() {
        return electrrequisitionno;
    }

    /**
     * Sets the value of the electrrequisitionno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setELECTRREQUISITIONNO(String value) {
        this.electrrequisitionno = value;
    }

    /**
     * Gets the value of the orderno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERNO() {
        return orderno;
    }

    /**
     * Sets the value of the orderno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERNO(String value) {
        this.orderno = value;
    }

    /**
     * Gets the value of the ordergroupno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERGROUPNO() {
        return ordergroupno;
    }

    /**
     * Sets the value of the ordergroupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERGROUPNO(String value) {
        this.ordergroupno = value;
    }

    /**
     * Gets the value of the reportno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTNO() {
        return reportno;
    }

    /**
     * Sets the value of the reportno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTNO(String value) {
        this.reportno = value;
    }

    /**
     * Gets the value of the testpatresourcecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTESTPATRESOURCECODE() {
        return testpatresourcecode;
    }

    /**
     * Sets the value of the testpatresourcecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTESTPATRESOURCECODE(String value) {
        this.testpatresourcecode = value;
    }

    /**
     * Gets the value of the testpatresourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTESTPATRESOURCENAME() {
        return testpatresourcename;
    }

    /**
     * Sets the value of the testpatresourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTESTPATRESOURCENAME(String value) {
        this.testpatresourcename = value;
    }

    /**
     * Gets the value of the reportname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTNAME() {
        return reportname;
    }

    /**
     * Sets the value of the reportname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTNAME(String value) {
        this.reportname = value;
    }

    /**
     * Gets the value of the applydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLYDATE() {
        return applydate;
    }

    /**
     * Sets the value of the applydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLYDATE(String value) {
        this.applydate = value;
    }

    /**
     * Gets the value of the testcategcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTESTCATEGCODE() {
        return testcategcode;
    }

    /**
     * Sets the value of the testcategcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTESTCATEGCODE(String value) {
        this.testcategcode = value;
    }

    /**
     * Gets the value of the testcategname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTESTCATEGNAME() {
        return testcategname;
    }

    /**
     * Sets the value of the testcategname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTESTCATEGNAME(String value) {
        this.testcategname = value;
    }

    /**
     * Gets the value of the executdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXECUTDATE() {
        return executdate;
    }

    /**
     * Sets the value of the executdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXECUTDATE(String value) {
        this.executdate = value;
    }

    /**
     * Gets the value of the reportdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTDATE() {
        return reportdate;
    }

    /**
     * Sets the value of the reportdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTDATE(String value) {
        this.reportdate = value;
    }

    /**
     * Gets the value of the sampleno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAMPLENO() {
        return sampleno;
    }

    /**
     * Sets the value of the sampleno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAMPLENO(String value) {
        this.sampleno = value;
    }

    /**
     * Gets the value of the microbetestflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMICROBETESTFLAG() {
        return microbetestflag;
    }

    /**
     * Sets the value of the microbetestflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMICROBETESTFLAG(String value) {
        this.microbetestflag = value;
    }

    /**
     * Gets the value of the applydeptindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLYDEPTINDEXNO() {
        return applydeptindexno;
    }

    /**
     * Sets the value of the applydeptindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLYDEPTINDEXNO(String value) {
        this.applydeptindexno = value;
    }

    /**
     * Gets the value of the applydeptcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLYDEPTCODE() {
        return applydeptcode;
    }

    /**
     * Sets the value of the applydeptcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLYDEPTCODE(String value) {
        this.applydeptcode = value;
    }

    /**
     * Gets the value of the applydeptname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLYDEPTNAME() {
        return applydeptname;
    }

    /**
     * Sets the value of the applydeptname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLYDEPTNAME(String value) {
        this.applydeptname = value;
    }

    /**
     * Gets the value of the executdeptindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXECUTDEPTINDEXNO() {
        return executdeptindexno;
    }

    /**
     * Sets the value of the executdeptindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXECUTDEPTINDEXNO(String value) {
        this.executdeptindexno = value;
    }

    /**
     * Gets the value of the executdeptcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXECUTDEPTCODE() {
        return executdeptcode;
    }

    /**
     * Sets the value of the executdeptcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXECUTDEPTCODE(String value) {
        this.executdeptcode = value;
    }

    /**
     * Gets the value of the executdeptname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXECUTDEPTNAME() {
        return executdeptname;
    }

    /**
     * Sets the value of the executdeptname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXECUTDEPTNAME(String value) {
        this.executdeptname = value;
    }

    /**
     * Gets the value of the applydrindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLYDRINDEXNO() {
        return applydrindexno;
    }

    /**
     * Sets the value of the applydrindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLYDRINDEXNO(String value) {
        this.applydrindexno = value;
    }

    /**
     * Gets the value of the applydrcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLYDRCODE() {
        return applydrcode;
    }

    /**
     * Sets the value of the applydrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLYDRCODE(String value) {
        this.applydrcode = value;
    }

    /**
     * Gets the value of the applydrname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLYDRNAME() {
        return applydrname;
    }

    /**
     * Sets the value of the applydrname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLYDRNAME(String value) {
        this.applydrname = value;
    }

    /**
     * Gets the value of the executdrindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXECUTDRINDEXNO() {
        return executdrindexno;
    }

    /**
     * Sets the value of the executdrindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXECUTDRINDEXNO(String value) {
        this.executdrindexno = value;
    }

    /**
     * Gets the value of the executdrcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXECUTDRCODE() {
        return executdrcode;
    }

    /**
     * Sets the value of the executdrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXECUTDRCODE(String value) {
        this.executdrcode = value;
    }

    /**
     * Gets the value of the executdrname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXECUTDRNAME() {
        return executdrname;
    }

    /**
     * Sets the value of the executdrname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXECUTDRNAME(String value) {
        this.executdrname = value;
    }

    /**
     * Gets the value of the reportdrindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTDRINDEXNO() {
        return reportdrindexno;
    }

    /**
     * Sets the value of the reportdrindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTDRINDEXNO(String value) {
        this.reportdrindexno = value;
    }

    /**
     * Gets the value of the reportdrcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTDRCODE() {
        return reportdrcode;
    }

    /**
     * Sets the value of the reportdrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTDRCODE(String value) {
        this.reportdrcode = value;
    }

    /**
     * Gets the value of the reportdrname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTDRNAME() {
        return reportdrname;
    }

    /**
     * Sets the value of the reportdrname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTDRNAME(String value) {
        this.reportdrname = value;
    }

    /**
     * Gets the value of the clinicdiagcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLINICDIAGCODE() {
        return clinicdiagcode;
    }

    /**
     * Sets the value of the clinicdiagcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLINICDIAGCODE(String value) {
        this.clinicdiagcode = value;
    }

    /**
     * Gets the value of the clinicdiagname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLINICDIAGNAME() {
        return clinicdiagname;
    }

    /**
     * Sets the value of the clinicdiagname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLINICDIAGNAME(String value) {
        this.clinicdiagname = value;
    }

    /**
     * Gets the value of the idnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNUMBER() {
        return idnumber;
    }

    /**
     * Sets the value of the idnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNUMBER(String value) {
        this.idnumber = value;
    }

    /**
     * Gets the value of the patname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATNAME() {
        return patname;
    }

    /**
     * Sets the value of the patname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATNAME(String value) {
        this.patname = value;
    }

    /**
     * Gets the value of the physisexcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHYSISEXCODE() {
        return physisexcode;
    }

    /**
     * Sets the value of the physisexcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHYSISEXCODE(String value) {
        this.physisexcode = value;
    }

    /**
     * Gets the value of the physisexname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHYSISEXNAME() {
        return physisexname;
    }

    /**
     * Sets the value of the physisexname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHYSISEXNAME(String value) {
        this.physisexname = value;
    }

    /**
     * Gets the value of the datebirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATEBIRTH() {
        return datebirth;
    }

    /**
     * Sets the value of the datebirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATEBIRTH(String value) {
        this.datebirth = value;
    }

    /**
     * Gets the value of the ethniccode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETHNICCODE() {
        return ethniccode;
    }

    /**
     * Sets the value of the ethniccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETHNICCODE(String value) {
        this.ethniccode = value;
    }

    /**
     * Gets the value of the ethnicname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETHNICNAME() {
        return ethnicname;
    }

    /**
     * Sets the value of the ethnicname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETHNICNAME(String value) {
        this.ethnicname = value;
    }

    /**
     * Gets the value of the maritalstatuscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARITALSTATUSCODE() {
        return maritalstatuscode;
    }

    /**
     * Sets the value of the maritalstatuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARITALSTATUSCODE(String value) {
        this.maritalstatuscode = value;
    }

    /**
     * Gets the value of the maritalstatusname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARITALSTATUSNAME() {
        return maritalstatusname;
    }

    /**
     * Sets the value of the maritalstatusname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARITALSTATUSNAME(String value) {
        this.maritalstatusname = value;
    }

    /**
     * Gets the value of the recorddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECORDDATE() {
        return recorddate;
    }

    /**
     * Sets the value of the recorddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECORDDATE(String value) {
        this.recorddate = value;
    }

    /**
     * Gets the value of the updatedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPDATEDATE() {
        return updatedate;
    }

    /**
     * Sets the value of the updatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPDATEDATE(String value) {
        this.updatedate = value;
    }

    /**
     * Gets the value of the equipmentcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEQUIPMENTCODE() {
        return equipmentcode;
    }

    /**
     * Sets the value of the equipmentcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEQUIPMENTCODE(String value) {
        this.equipmentcode = value;
    }

    /**
     * Gets the value of the equipmentname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEQUIPMENTNAME() {
        return equipmentname;
    }

    /**
     * Sets the value of the equipmentname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEQUIPMENTNAME(String value) {
        this.equipmentname = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTE() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTE(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
