//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 03:08:49 PM CST 
//


package com.zebone.nhis.ma.pub.platform.receive.yh.vo.AdtRegister;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PAT_NAME"/>
 *         &lt;element ref="{}CERTIFICATE_TYPE"/>
 *         &lt;element ref="{}CERTIFICATE_NO"/>
 *         &lt;element ref="{}PHYSI_SEX_CODE"/>
 *         &lt;element ref="{}DATE_BIRTH"/>
 *         &lt;element ref="{}NATION_CODE"/>
 *         &lt;element ref="{}ETHNIC_CODE"/>
 *         &lt;element ref="{}MARITAL_STATUS_CODE"/>
 *         &lt;element ref="{}PHONE_NO"/>
 *         &lt;element ref="{}CURR_ADDR"/>
 *         &lt;element ref="{}HUKOU_ADDR"/>
 *         &lt;element ref="{}COMPANY"/>
 *         &lt;element ref="{}CONTACT_NAME"/>
 *         &lt;element ref="{}CONTACT_RELATION_CODE"/>
 *         &lt;element ref="{}CONTACT_PHONE_NO"/>
 *         &lt;element ref="{}INHOSP_NO"/>
 *         &lt;element ref="{}ADMIT_DATE"/>
 *         &lt;element ref="{}RECEPT_TREAT_DR_CODE"/>
 *         &lt;element ref="{}ADMIT_WARD_CODE"/>
 *         &lt;element ref="{}ADMIT_WAY_CODE"/>
 *         &lt;element ref="{}ADMIT_DIAG_CODE"/>
 *         &lt;element ref="{}MED_PLAN"/>
 *         &lt;element ref="{}PAT_TYPE"/>
 *         &lt;element ref="{}DISE_LEVEL"/>
 *         &lt;element ref="{}ADMIT_DEPT"/>
 *         &lt;element ref="{}ADMIT_TIMES"/>
 *         &lt;element ref="{}PAT_INDEX_NO"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patname",
    "certificatetype",
    "certificateno",
    "physisexcode",
    "datebirth",
    "nationcode",
    "ethniccode",
    "maritalstatuscode",
    "phoneno",
    "curraddr",
    "hukouaddr",
    "company",
    "contactname",
    "contactrelationcode",
    "contactphoneno",
    "inhospno",
    "admitdate",
    "recepttreatdrcode",
    "admitwardcode",
    "admitwaycode",
    "admitdiagcode",
    "medplan",
    "pattype",
    "diselevel",
    "admitdept",
    "admittimes",
    "patindexno"
})
@XmlRootElement(name = "Msg")
public class AdtRegisterInfo {

    @XmlElement(name = "PAT_NAME", required = true)
    protected String patname;
    @XmlElement(name = "CERTIFICATE_TYPE", required = true)
    protected String certificatetype;
    @XmlElement(name = "CERTIFICATE_NO", required = true)
    protected String certificateno;
    @XmlElement(name = "PHYSI_SEX_CODE", required = true)
    protected String physisexcode;
    @XmlElement(name = "DATE_BIRTH", required = true)
    protected String datebirth;
    @XmlElement(name = "NATION_CODE", required = true)
    protected String nationcode;
    @XmlElement(name = "ETHNIC_CODE", required = true)
    protected String ethniccode;
    @XmlElement(name = "MARITAL_STATUS_CODE", required = true)
    protected String maritalstatuscode;
    @XmlElement(name = "PHONE_NO", required = true)
    protected String phoneno;
    @XmlElement(name = "CURR_ADDR", required = true)
    protected String curraddr;
    @XmlElement(name = "HUKOU_ADDR", required = true)
    protected String hukouaddr;
    @XmlElement(name = "COMPANY", required = true)
    protected String company;
    @XmlElement(name = "CONTACT_NAME", required = true)
    protected String contactname;
    @XmlElement(name = "CONTACT_RELATION_CODE", required = true)
    protected String contactrelationcode;
    @XmlElement(name = "CONTACT_PHONE_NO", required = true)
    protected String contactphoneno;
    @XmlElement(name = "INHOSP_NO", required = true)
    protected String inhospno;
    @XmlElement(name = "ADMIT_DATE", required = true)
    protected String admitdate;
    @XmlElement(name = "RECEPT_TREAT_DR_CODE", required = true)
    protected String recepttreatdrcode;
    @XmlElement(name = "ADMIT_WARD_CODE", required = true)
    protected String admitwardcode;
    @XmlElement(name = "ADMIT_WAY_CODE", required = true)
    protected String admitwaycode;
    @XmlElement(name = "ADMIT_DIAG_CODE", required = true)
    protected String admitdiagcode;
    @XmlElement(name = "MED_PLAN", required = true)
    protected String medplan;
    @XmlElement(name = "PAT_TYPE", required = true)
    protected String pattype;
    @XmlElement(name = "DISE_LEVEL", required = true)
    protected String diselevel;
    @XmlElement(name = "ADMIT_DEPT", required = true)
    protected String admitdept;
    @XmlElement(name = "ADMIT_TIMES", required = true)
    protected String admittimes;
    @XmlElement(name = "PAT_INDEX_NO", required = true)
    protected String patindexno;
    @XmlAttribute(name = "action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String action;

    /**
     * Gets the value of the patname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATNAME() {
        return patname;
    }

    /**
     * Sets the value of the patname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATNAME(String value) {
        this.patname = value;
    }

    /**
     * Gets the value of the certificatetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCERTIFICATETYPE() {
        return certificatetype;
    }

    /**
     * Sets the value of the certificatetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCERTIFICATETYPE(String value) {
        this.certificatetype = value;
    }

    /**
     * Gets the value of the certificateno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCERTIFICATENO() {
        return certificateno;
    }

    /**
     * Sets the value of the certificateno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCERTIFICATENO(String value) {
        this.certificateno = value;
    }

    /**
     * Gets the value of the physisexcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHYSISEXCODE() {
        return physisexcode;
    }

    /**
     * Sets the value of the physisexcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHYSISEXCODE(String value) {
        this.physisexcode = value;
    }

    /**
     * Gets the value of the datebirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATEBIRTH() {
        return datebirth;
    }

    /**
     * Sets the value of the datebirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATEBIRTH(String value) {
        this.datebirth = value;
    }

    /**
     * Gets the value of the nationcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONCODE() {
        return nationcode;
    }

    /**
     * Sets the value of the nationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONCODE(String value) {
        this.nationcode = value;
    }

    /**
     * Gets the value of the ethniccode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETHNICCODE() {
        return ethniccode;
    }

    /**
     * Sets the value of the ethniccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETHNICCODE(String value) {
        this.ethniccode = value;
    }

    /**
     * Gets the value of the maritalstatuscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARITALSTATUSCODE() {
        return maritalstatuscode;
    }

    /**
     * Sets the value of the maritalstatuscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARITALSTATUSCODE(String value) {
        this.maritalstatuscode = value;
    }

    /**
     * Gets the value of the phoneno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONENO() {
        return phoneno;
    }

    /**
     * Sets the value of the phoneno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONENO(String value) {
        this.phoneno = value;
    }

    /**
     * Gets the value of the curraddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRADDR() {
        return curraddr;
    }

    /**
     * Sets the value of the curraddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRADDR(String value) {
        this.curraddr = value;
    }

    /**
     * Gets the value of the hukouaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHUKOUADDR() {
        return hukouaddr;
    }

    /**
     * Sets the value of the hukouaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHUKOUADDR(String value) {
        this.hukouaddr = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPANY() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPANY(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the contactname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTACTNAME() {
        return contactname;
    }

    /**
     * Sets the value of the contactname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTACTNAME(String value) {
        this.contactname = value;
    }

    /**
     * Gets the value of the contactrelationcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTACTRELATIONCODE() {
        return contactrelationcode;
    }

    /**
     * Sets the value of the contactrelationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTACTRELATIONCODE(String value) {
        this.contactrelationcode = value;
    }

    /**
     * Gets the value of the contactphoneno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTACTPHONENO() {
        return contactphoneno;
    }

    /**
     * Sets the value of the contactphoneno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTACTPHONENO(String value) {
        this.contactphoneno = value;
    }

    /**
     * Gets the value of the inhospno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINHOSPNO() {
        return inhospno;
    }

    /**
     * Sets the value of the inhospno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINHOSPNO(String value) {
        this.inhospno = value;
    }

    /**
     * Gets the value of the admitdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMITDATE() {
        return admitdate;
    }

    /**
     * Sets the value of the admitdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMITDATE(String value) {
        this.admitdate = value;
    }

    /**
     * Gets the value of the recepttreatdrcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEPTTREATDRCODE() {
        return recepttreatdrcode;
    }

    /**
     * Sets the value of the recepttreatdrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEPTTREATDRCODE(String value) {
        this.recepttreatdrcode = value;
    }

    /**
     * Gets the value of the admitwardcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMITWARDCODE() {
        return admitwardcode;
    }

    /**
     * Sets the value of the admitwardcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMITWARDCODE(String value) {
        this.admitwardcode = value;
    }

    /**
     * Gets the value of the admitwaycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMITWAYCODE() {
        return admitwaycode;
    }

    /**
     * Sets the value of the admitwaycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMITWAYCODE(String value) {
        this.admitwaycode = value;
    }

    /**
     * Gets the value of the admitdiagcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMITDIAGCODE() {
        return admitdiagcode;
    }

    /**
     * Sets the value of the admitdiagcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMITDIAGCODE(String value) {
        this.admitdiagcode = value;
    }

    /**
     * Gets the value of the medplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEDPLAN() {
        return medplan;
    }

    /**
     * Sets the value of the medplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEDPLAN(String value) {
        this.medplan = value;
    }

    /**
     * Gets the value of the pattype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATTYPE() {
        return pattype;
    }

    /**
     * Sets the value of the pattype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATTYPE(String value) {
        this.pattype = value;
    }

    /**
     * Gets the value of the diselevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISELEVEL() {
        return diselevel;
    }

    /**
     * Sets the value of the diselevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISELEVEL(String value) {
        this.diselevel = value;
    }

    /**
     * Gets the value of the admitdept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMITDEPT() {
        return admitdept;
    }

    /**
     * Sets the value of the admitdept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMITDEPT(String value) {
        this.admitdept = value;
    }

    /**
     * Gets the value of the admisstimes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADMITTIMES() {
        return admittimes;
    }

    /**
     * Sets the value of the admittimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADMITTIMES(String value) {
        this.admittimes = value;
    }

    /**
     * Gets the value of the patindexno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATINDEXNO() {
        return patindexno;
    }

    /**
     * Sets the value of the patindexno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATINDEXNO(String value) {
        this.patindexno = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
