//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.14 at 05:01:10 PM CST 
//


package com.zebone.nhis.ma.pub.platform.receive.yh.vo.AdtRegister;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HUKOUADDR_QNAME = new QName("", "HUKOU_ADDR");
    private final static QName _PHYSISEXCODE_QNAME = new QName("", "PHYSI_SEX_CODE");
    private final static QName _NATIONCODE_QNAME = new QName("", "NATION_CODE");
    private final static QName _CONTACTNAME_QNAME = new QName("", "CONTACT_NAME");
    private final static QName _ReturnFlag_QNAME = new QName("", "ReturnFlag");
    private final static QName _Password_QNAME = new QName("", "Password");
    private final static QName _CURRADDR_QNAME = new QName("", "CURR_ADDR");
    private final static QName _DISELEVEL_QNAME = new QName("", "DISE_LEVEL");
    private final static QName _UserName_QNAME = new QName("", "UserName");
    private final static QName _MsgDate_QNAME = new QName("", "MsgDate");
    private final static QName _MARITALSTATUSCODE_QNAME = new QName("", "MARITAL_STATUS_CODE");
    private final static QName _ADMITWAYCODE_QNAME = new QName("", "ADMIT_WAY_CODE");
    private final static QName _PHONENO_QNAME = new QName("", "PHONE_NO");
    private final static QName _SysFlag_QNAME = new QName("", "SysFlag");
    private final static QName _INHOSPNO_QNAME = new QName("", "INHOSP_NO");
    private final static QName _ETHNICCODE_QNAME = new QName("", "ETHNIC_CODE");
    private final static QName _RECEPTTREATDRCODE_QNAME = new QName("", "RECEPT_TREAT_DR_CODE");
    private final static QName _ADMITDEPT_QNAME = new QName("", "ADMIT_DEPT");
    private final static QName _COMPANY_QNAME = new QName("", "COMPANY");
    private final static QName _SourceSysCode_QNAME = new QName("", "SourceSysCode");
    private final static QName _ADMITDIAGCODE_QNAME = new QName("", "ADMIT_DIAG_CODE");
    private final static QName _Fid_QNAME = new QName("", "Fid");
    private final static QName _PATNAME_QNAME = new QName("", "PAT_NAME");
    private final static QName _CONTACTPHONENO_QNAME = new QName("", "CONTACT_PHONE_NO");
    private final static QName _MEDPLAN_QNAME = new QName("", "MED_PLAN");
    private final static QName _CERTIFICATETYPE_QNAME = new QName("", "CERTIFICATE_TYPE");
    private final static QName _CONTACTRELATIONCODE_QNAME = new QName("", "CONTACT_RELATION_CODE");
    private final static QName _ADMITWARDCODE_QNAME = new QName("", "ADMIT_WARD_CODE");
    private final static QName _TargetSysCode_QNAME = new QName("", "TargetSysCode");
    private final static QName _ADMITDATE_QNAME = new QName("", "ADMIT_DATE");
    private final static QName _CERTIFICATENO_QNAME = new QName("", "CERTIFICATE_NO");
    private final static QName _PATTYPE_QNAME = new QName("", "PAT_TYPE");
    private final static QName _DATEBIRTH_QNAME = new QName("", "DATE_BIRTH");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MsgInfo }
     * 
     */
    public MsgInfo createMsgInfo() {
        return new MsgInfo();
    }

    /**
     * Create an instance of {@link AdtRegisterInfo }
     * 
     */
    public AdtRegisterInfo createMsg() {
        return new AdtRegisterInfo();
    }

    /**
     * Create an instance of {@link MessageHeader }
     * 
     */
    public MessageHeader createMessageHeader() {
        return new MessageHeader();
    }

    /**
     * Create an instance of {@link AdtRegisterESBEntry }
     * 
     */
    public AdtRegisterESBEntry createESBEntry() {
        return new AdtRegisterESBEntry();
    }

    /**
     * Create an instance of {@link AccessControl }
     * 
     */
    public AccessControl createAccessControl() {
        return new AccessControl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HUKOU_ADDR")
    public JAXBElement<String> createHUKOUADDR(String value) {
        return new JAXBElement<String>(_HUKOUADDR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PHYSI_SEX_CODE")
    public JAXBElement<String> createPHYSISEXCODE(String value) {
        return new JAXBElement<String>(_PHYSISEXCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NATION_CODE")
    public JAXBElement<String> createNATIONCODE(String value) {
        return new JAXBElement<String>(_NATIONCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTACT_NAME")
    public JAXBElement<String> createCONTACTNAME(String value) {
        return new JAXBElement<String>(_CONTACTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReturnFlag")
    public JAXBElement<BigInteger> createReturnFlag(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReturnFlag_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Password")
    public JAXBElement<BigInteger> createPassword(BigInteger value) {
        return new JAXBElement<BigInteger>(_Password_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CURR_ADDR")
    public JAXBElement<String> createCURRADDR(String value) {
        return new JAXBElement<String>(_CURRADDR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DISE_LEVEL")
    public JAXBElement<String> createDISELEVEL(String value) {
        return new JAXBElement<String>(_DISELEVEL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgDate")
    public JAXBElement<String> createMsgDate(String value) {
        return new JAXBElement<String>(_MsgDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MARITAL_STATUS_CODE")
    public JAXBElement<String> createMARITALSTATUSCODE(String value) {
        return new JAXBElement<String>(_MARITALSTATUSCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADMIT_WAY_CODE")
    public JAXBElement<String> createADMITWAYCODE(String value) {
        return new JAXBElement<String>(_ADMITWAYCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PHONE_NO")
    public JAXBElement<String> createPHONENO(String value) {
        return new JAXBElement<String>(_PHONENO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SysFlag")
    public JAXBElement<BigInteger> createSysFlag(BigInteger value) {
        return new JAXBElement<BigInteger>(_SysFlag_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INHOSP_NO")
    public JAXBElement<String> createINHOSPNO(String value) {
        return new JAXBElement<String>(_INHOSPNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ETHNIC_CODE")
    public JAXBElement<String> createETHNICCODE(String value) {
        return new JAXBElement<String>(_ETHNICCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RECEPT_TREAT_DR_CODE")
    public JAXBElement<String> createRECEPTTREATDRCODE(String value) {
        return new JAXBElement<String>(_RECEPTTREATDRCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADMIT_DEPT")
    public JAXBElement<String> createADMITDEPT(String value) {
        return new JAXBElement<String>(_ADMITDEPT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPANY")
    public JAXBElement<String> createCOMPANY(String value) {
        return new JAXBElement<String>(_COMPANY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SourceSysCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSourceSysCode(String value) {
        return new JAXBElement<String>(_SourceSysCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADMIT_DIAG_CODE")
    public JAXBElement<String> createADMITDIAGCODE(String value) {
        return new JAXBElement<String>(_ADMITDIAGCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFid(String value) {
        return new JAXBElement<String>(_Fid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAT_NAME")
    public JAXBElement<String> createPATNAME(String value) {
        return new JAXBElement<String>(_PATNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTACT_PHONE_NO")
    public JAXBElement<String> createCONTACTPHONENO(String value) {
        return new JAXBElement<String>(_CONTACTPHONENO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MED_PLAN")
    public JAXBElement<String> createMEDPLAN(String value) {
        return new JAXBElement<String>(_MEDPLAN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CERTIFICATE_TYPE")
    public JAXBElement<String> createCERTIFICATETYPE(String value) {
        return new JAXBElement<String>(_CERTIFICATETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTACT_RELATION_CODE")
    public JAXBElement<String> createCONTACTRELATIONCODE(String value) {
        return new JAXBElement<String>(_CONTACTRELATIONCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADMIT_WARD_CODE")
    public JAXBElement<String> createADMITWARDCODE(String value) {
        return new JAXBElement<String>(_ADMITWARDCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TargetSysCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTargetSysCode(String value) {
        return new JAXBElement<String>(_TargetSysCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADMIT_DATE")
    public JAXBElement<String> createADMITDATE(String value) {
        return new JAXBElement<String>(_ADMITDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CERTIFICATE_NO")
    public JAXBElement<String> createCERTIFICATENO(String value) {
        return new JAXBElement<String>(_CERTIFICATENO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PAT_TYPE")
    public JAXBElement<String> createPATTYPE(String value) {
        return new JAXBElement<String>(_PATTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATE_BIRTH")
    public JAXBElement<String> createDATEBIRTH(String value) {
        return new JAXBElement<String>(_DATEBIRTH_QNAME, String.class, null, value);
    }

}
