//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.26 at 03:17:42 PM CST 
//


package com.zebone.nhis.webservice.vo.ticketvo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}scheList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scheList"
})
@XmlRootElement(name = "data")
public class Data {

    @XmlElement(required = true)
    protected ScheList scheList;

    /**
     * Gets the value of the scheList property.
     * 
     * @return
     *     possible object is
     *     {@link ScheList }
     *     
     */
    public ScheList getScheList() {
        return scheList;
    }

    /**
     * Sets the value of the scheList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheList }
     *     
     */
    public void setScheList(ScheList value) {
        this.scheList = value;
    }

}
