//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 05:04:36 PM CST
//


package com.zebone.nhis.ma.pub.platform.send.impl.yh.vo.CheckReport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OUTHOSP_INDEX_NO"/>
 *         &lt;element ref="{}OUTHOSP_NO"/>
 *         &lt;element ref="{}INHOSP_INDEX_NO"/>
 *         &lt;element ref="{}MR_NO"/>
 *         &lt;element ref="{}ANAMNESIS_NO"/>
 *         &lt;element ref="{}VISIT_CARD_NO"/>
 *         &lt;element ref="{}INHOSP_NUM"/>
 *         &lt;element ref="{}INHOSP_NO"/>
 *         &lt;element ref="{}PAT_INDEX_NO"/>
 *         &lt;element ref="{}ELECTR_REQUISITION_NO"/>
 *         &lt;element ref="{}ORDER_NO"/>
 *         &lt;element ref="{}ORDER_GROUP_NO"/>
 *         &lt;element ref="{}REPORT_NO"/>
 *         &lt;element ref="{}REPORT_NAME"/>
 *         &lt;element ref="{}EXAM_PAT_RESOURCE_CODE"/>
 *         &lt;element ref="{}EXAM_PAT_RESOURCE_NAME"/>
 *         &lt;element ref="{}APPLY_DATE"/>
 *         &lt;element ref="{}EXECUT_DATE"/>
 *         &lt;element ref="{}REPORT_DATE"/>
 *         &lt;element ref="{}OPER_PART_CODE"/>
 *         &lt;element ref="{}OPER_PART_NAME"/>
 *         &lt;element ref="{}EXAM_CATEG_CODE"/>
 *         &lt;element ref="{}EXAM_CATEG_NAME"/>
 *         &lt;element ref="{}EXAM_METHOD_CODE"/>
 *         &lt;element ref="{}EXAM_METHOD_NAME"/>
 *         &lt;element ref="{}EXAM_ITEM_CODE"/>
 *         &lt;element ref="{}EXAM_ITEM_NAME"/>
 *         &lt;element ref="{}EXAM_RESULT"/>
 *         &lt;element ref="{}EXAM_DESCR"/>
 *         &lt;element ref="{}APPLY_DEPT_INDEX_NO"/>
 *         &lt;element ref="{}APPLY_DEPT_CODE"/>
 *         &lt;element ref="{}APPLY_DEPT_NAME"/>
 *         &lt;element ref="{}EXECUT_DEPT_INDEX_NO"/>
 *         &lt;element ref="{}EXECUT_DEPT_CODE"/>
 *         &lt;element ref="{}EXECUT_DEPT_NAME"/>
 *         &lt;element ref="{}APPLY_DR_INDEX_NO"/>
 *         &lt;element ref="{}APPLY_DR_CODE"/>
 *         &lt;element ref="{}APPLY_DR_NAME"/>
 *         &lt;element ref="{}EXECUT_DR_INDEX_NO"/>
 *         &lt;element ref="{}EXECUT_DR_CODE"/>
 *         &lt;element ref="{}EXECUT_DR_NAME"/>
 *         &lt;element ref="{}REPORT_DR_INDEX_NO"/>
 *         &lt;element ref="{}REPORT_DR_CODE"/>
 *         &lt;element ref="{}REPORT_DR_NAME"/>
 *         &lt;element ref="{}CLINIC_DIAG_CODE"/>
 *         &lt;element ref="{}CLINIC_DIAG_NAME"/>
 *         &lt;element ref="{}ID_NUMBER"/>
 *         &lt;element ref="{}PAT_NAME"/>
 *         &lt;element ref="{}PHYSI_SEX_CODE"/>
 *         &lt;element ref="{}PHYSI_SEX_NAME"/>
 *         &lt;element ref="{}DATE_BIRTH"/>
 *         &lt;element ref="{}ETHNIC_CODE"/>
 *         &lt;element ref="{}ETHNIC_NAME"/>
 *         &lt;element ref="{}MARITAL_STATUS_CODE"/>
 *         &lt;element ref="{}MARITAL_STATUS_NAME"/>
 *         &lt;element ref="{}RECORD_DATE"/>
 *         &lt;element ref="{}UPDATE_DATE"/>
 *         &lt;element ref="{}EQUIPMENT_CODE"/>
 *         &lt;element ref="{}EQUIPMENT_NAME"/>
 *         &lt;element ref="{}NOTE"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "outhospindexno",
        "outhospno",
        "inhospindexno",
        "mrno",
        "anamnesisno",
        "visitcardno",
        "inhospnum",
        "inhospno",
        "patindexno",
        "electrrequisitionno",
        "orderno",
        "ordergroupno",
        "reportno",
        "reportname",
        "exampatresourcecode",
        "exampatresourcename",
        "applydate",
        "executdate",
        "reportdate",
        "operpartcode",
        "operpartname",
        "examcategcode",
        "examcategname",
        "exammethodcode",
        "exammethodname",
        "examitemcode",
        "examitemname",
        "examresult",
        "examdescr",
        "applydeptindexno",
        "applydeptcode",
        "applydeptname",
        "executdeptindexno",
        "executdeptcode",
        "executdeptname",
        "applydrindexno",
        "applydrcode",
        "applydrname",
        "executdrindexno",
        "executdrcode",
        "executdrname",
        "reportdrindexno",
        "reportdrcode",
        "reportdrname",
        "clinicdiagcode",
        "clinicdiagname",
        "idnumber",
        "patname",
        "physisexcode",
        "physisexname",
        "datebirth",
        "ethniccode",
        "ethnicname",
        "maritalstatuscode",
        "maritalstatusname",
        "recorddate",
        "updatedate",
        "equipmentcode",
        "equipmentname",
        "note"
})
@XmlRootElement(name = "row")
public class CheckReportRow {

    @XmlElement(name = "OUTHOSP_INDEX_NO", required = true)
    protected String outhospindexno;
    @XmlElement(name = "OUTHOSP_NO", required = true)
    protected String outhospno;
    @XmlElement(name = "INHOSP_INDEX_NO", required = true)
    protected String inhospindexno;
    @XmlElement(name = "MR_NO", required = true)
    protected String mrno;
    @XmlElement(name = "ANAMNESIS_NO", required = true)
    protected String anamnesisno;
    @XmlElement(name = "VISIT_CARD_NO", required = true)
    protected String visitcardno;
    @XmlElement(name = "INHOSP_NUM", required = true)
    protected String inhospnum;
    @XmlElement(name = "INHOSP_NO", required = true)
    protected String inhospno;
    @XmlElement(name = "PAT_INDEX_NO", required = true)
    protected String patindexno;
    @XmlElement(name = "ELECTR_REQUISITION_NO", required = true)
    protected String electrrequisitionno;
    @XmlElement(name = "ORDER_NO", required = true)
    protected String orderno;
    @XmlElement(name = "ORDER_GROUP_NO", required = true)
    protected String ordergroupno;
    @XmlElement(name = "REPORT_NO", required = true)
    protected String reportno;
    @XmlElement(name = "REPORT_NAME", required = true)
    protected String reportname;
    @XmlElement(name = "EXAM_PAT_RESOURCE_CODE", required = true)
    protected String exampatresourcecode;
    @XmlElement(name = "EXAM_PAT_RESOURCE_NAME", required = true)
    protected String exampatresourcename;
    @XmlElement(name = "APPLY_DATE", required = true)
    protected String applydate;
    @XmlElement(name = "EXECUT_DATE", required = true)
    protected String executdate;
    @XmlElement(name = "REPORT_DATE", required = true)
    protected String reportdate;
    @XmlElement(name = "OPER_PART_CODE", required = true)
    protected String operpartcode;
    @XmlElement(name = "OPER_PART_NAME", required = true)
    protected String operpartname;
    @XmlElement(name = "EXAM_CATEG_CODE", required = true)
    protected String examcategcode;
    @XmlElement(name = "EXAM_CATEG_NAME", required = true)
    protected String examcategname;
    @XmlElement(name = "EXAM_METHOD_CODE", required = true)
    protected String exammethodcode;
    @XmlElement(name = "EXAM_METHOD_NAME", required = true)
    protected String exammethodname;
    @XmlElement(name = "EXAM_ITEM_CODE", required = true)
    protected String examitemcode;
    @XmlElement(name = "EXAM_ITEM_NAME", required = true)
    protected String examitemname;
    @XmlElement(name = "EXAM_RESULT", required = true)
    protected String examresult;
    @XmlElement(name = "EXAM_DESCR", required = true)
    protected String examdescr;
    @XmlElement(name = "APPLY_DEPT_INDEX_NO", required = true)
    protected String applydeptindexno;
    @XmlElement(name = "APPLY_DEPT_CODE", required = true)
    protected String applydeptcode;
    @XmlElement(name = "APPLY_DEPT_NAME", required = true)
    protected String applydeptname;
    @XmlElement(name = "EXECUT_DEPT_INDEX_NO", required = true)
    protected String executdeptindexno;
    @XmlElement(name = "EXECUT_DEPT_CODE", required = true)
    protected String executdeptcode;
    @XmlElement(name = "EXECUT_DEPT_NAME", required = true)
    protected String executdeptname;
    @XmlElement(name = "APPLY_DR_INDEX_NO", required = true)
    protected String applydrindexno;
    @XmlElement(name = "APPLY_DR_CODE", required = true)
    protected String applydrcode;
    @XmlElement(name = "APPLY_DR_NAME", required = true)
    protected String applydrname;
    @XmlElement(name = "EXECUT_DR_INDEX_NO", required = true)
    protected String executdrindexno;
    @XmlElement(name = "EXECUT_DR_CODE", required = true)
    protected String executdrcode;
    @XmlElement(name = "EXECUT_DR_NAME", required = true)
    protected String executdrname;
    @XmlElement(name = "REPORT_DR_INDEX_NO", required = true)
    protected String reportdrindexno;
    @XmlElement(name = "REPORT_DR_CODE", required = true)
    protected String reportdrcode;
    @XmlElement(name = "REPORT_DR_NAME", required = true)
    protected String reportdrname;
    @XmlElement(name = "CLINIC_DIAG_CODE", required = true)
    protected String clinicdiagcode;
    @XmlElement(name = "CLINIC_DIAG_NAME", required = true)
    protected String clinicdiagname;
    @XmlElement(name = "ID_NUMBER", required = true)
    protected String idnumber;
    @XmlElement(name = "PAT_NAME", required = true)
    protected String patname;
    @XmlElement(name = "PHYSI_SEX_CODE", required = true)
    protected String physisexcode;
    @XmlElement(name = "PHYSI_SEX_NAME", required = true)
    protected String physisexname;
    @XmlElement(name = "DATE_BIRTH", required = true)
    protected String datebirth;
    @XmlElement(name = "ETHNIC_CODE", required = true)
    protected String ethniccode;
    @XmlElement(name = "ETHNIC_NAME", required = true)
    protected String ethnicname;
    @XmlElement(name = "MARITAL_STATUS_CODE", required = true)
    protected String maritalstatuscode;
    @XmlElement(name = "MARITAL_STATUS_NAME", required = true)
    protected String maritalstatusname;
    @XmlElement(name = "RECORD_DATE", required = true)
    protected String recorddate;
    @XmlElement(name = "UPDATE_DATE", required = true)
    protected String updatedate;
    @XmlElement(name = "EQUIPMENT_CODE", required = true)
    protected String equipmentcode;
    @XmlElement(name = "EQUIPMENT_NAME", required = true)
    protected String equipmentname;
    @XmlElement(name = "NOTE", required = true)
    protected String note;
    @XmlAttribute(name = "action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String action;

    /**
     * Gets the value of the outhospindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOUTHOSPINDEXNO() {
        return outhospindexno;
    }

    /**
     * Sets the value of the outhospindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOUTHOSPINDEXNO(String value) {
        this.outhospindexno = value;
    }

    /**
     * Gets the value of the outhospno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOUTHOSPNO() {
        return outhospno;
    }

    /**
     * Sets the value of the outhospno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOUTHOSPNO(String value) {
        this.outhospno = value;
    }

    /**
     * Gets the value of the inhospindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getINHOSPINDEXNO() {
        return inhospindexno;
    }

    /**
     * Sets the value of the inhospindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setINHOSPINDEXNO(String value) {
        this.inhospindexno = value;
    }

    /**
     * Gets the value of the mrno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMRNO() {
        return mrno;
    }

    /**
     * Sets the value of the mrno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMRNO(String value) {
        this.mrno = value;
    }

    /**
     * Gets the value of the anamnesisno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getANAMNESISNO() {
        return anamnesisno;
    }

    /**
     * Sets the value of the anamnesisno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setANAMNESISNO(String value) {
        this.anamnesisno = value;
    }

    /**
     * Gets the value of the visitcardno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVISITCARDNO() {
        return visitcardno;
    }

    /**
     * Sets the value of the visitcardno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVISITCARDNO(String value) {
        this.visitcardno = value;
    }

    /**
     * Gets the value of the inhospnum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getINHOSPNUM() {
        return inhospnum;
    }

    /**
     * Sets the value of the inhospnum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setINHOSPNUM(String value) {
        this.inhospnum = value;
    }

    /**
     * Gets the value of the inhospno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getINHOSPNO() {
        return inhospno;
    }

    /**
     * Sets the value of the inhospno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setINHOSPNO(String value) {
        this.inhospno = value;
    }

    /**
     * Gets the value of the patindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPATINDEXNO() {
        return patindexno;
    }

    /**
     * Sets the value of the patindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPATINDEXNO(String value) {
        this.patindexno = value;
    }

    /**
     * Gets the value of the electrrequisitionno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getELECTRREQUISITIONNO() {
        return electrrequisitionno;
    }

    /**
     * Sets the value of the electrrequisitionno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setELECTRREQUISITIONNO(String value) {
        this.electrrequisitionno = value;
    }

    /**
     * Gets the value of the orderno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getORDERNO() {
        return orderno;
    }

    /**
     * Sets the value of the orderno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setORDERNO(String value) {
        this.orderno = value;
    }

    /**
     * Gets the value of the ordergroupno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getORDERGROUPNO() {
        return ordergroupno;
    }

    /**
     * Sets the value of the ordergroupno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setORDERGROUPNO(String value) {
        this.ordergroupno = value;
    }

    /**
     * Gets the value of the reportno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getREPORTNO() {
        return reportno;
    }

    /**
     * Sets the value of the reportno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setREPORTNO(String value) {
        this.reportno = value;
    }

    /**
     * Gets the value of the reportname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getREPORTNAME() {
        return reportname;
    }

    /**
     * Sets the value of the reportname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setREPORTNAME(String value) {
        this.reportname = value;
    }

    /**
     * Gets the value of the exampatresourcecode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMPATRESOURCECODE() {
        return exampatresourcecode;
    }

    /**
     * Sets the value of the exampatresourcecode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMPATRESOURCECODE(String value) {
        this.exampatresourcecode = value;
    }

    /**
     * Gets the value of the exampatresourcename property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMPATRESOURCENAME() {
        return exampatresourcename;
    }

    /**
     * Sets the value of the exampatresourcename property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMPATRESOURCENAME(String value) {
        this.exampatresourcename = value;
    }

    /**
     * Gets the value of the applydate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAPPLYDATE() {
        return applydate;
    }

    /**
     * Sets the value of the applydate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAPPLYDATE(String value) {
        this.applydate = value;
    }

    /**
     * Gets the value of the executdate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXECUTDATE() {
        return executdate;
    }

    /**
     * Sets the value of the executdate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXECUTDATE(String value) {
        this.executdate = value;
    }

    /**
     * Gets the value of the reportdate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getREPORTDATE() {
        return reportdate;
    }

    /**
     * Sets the value of the reportdate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setREPORTDATE(String value) {
        this.reportdate = value;
    }

    /**
     * Gets the value of the operpartcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOPERPARTCODE() {
        return operpartcode;
    }

    /**
     * Sets the value of the operpartcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOPERPARTCODE(String value) {
        this.operpartcode = value;
    }

    /**
     * Gets the value of the operpartname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOPERPARTNAME() {
        return operpartname;
    }

    /**
     * Sets the value of the operpartname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOPERPARTNAME(String value) {
        this.operpartname = value;
    }

    /**
     * Gets the value of the examcategcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMCATEGCODE() {
        return examcategcode;
    }

    /**
     * Sets the value of the examcategcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMCATEGCODE(String value) {
        this.examcategcode = value;
    }

    /**
     * Gets the value of the examcategname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMCATEGNAME() {
        return examcategname;
    }

    /**
     * Sets the value of the examcategname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMCATEGNAME(String value) {
        this.examcategname = value;
    }

    /**
     * Gets the value of the exammethodcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMMETHODCODE() {
        return exammethodcode;
    }

    /**
     * Sets the value of the exammethodcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMMETHODCODE(String value) {
        this.exammethodcode = value;
    }

    /**
     * Gets the value of the exammethodname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMMETHODNAME() {
        return exammethodname;
    }

    /**
     * Sets the value of the exammethodname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMMETHODNAME(String value) {
        this.exammethodname = value;
    }

    /**
     * Gets the value of the examitemcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMITEMCODE() {
        return examitemcode;
    }

    /**
     * Sets the value of the examitemcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMITEMCODE(String value) {
        this.examitemcode = value;
    }

    /**
     * Gets the value of the examitemname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMITEMNAME() {
        return examitemname;
    }

    /**
     * Sets the value of the examitemname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMITEMNAME(String value) {
        this.examitemname = value;
    }

    /**
     * Gets the value of the examresult property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMRESULT() {
        return examresult;
    }

    /**
     * Sets the value of the examresult property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMRESULT(String value) {
        this.examresult = value;
    }

    /**
     * Gets the value of the examdescr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXAMDESCR() {
        return examdescr;
    }

    /**
     * Sets the value of the examdescr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXAMDESCR(String value) {
        this.examdescr = value;
    }

    /**
     * Gets the value of the applydeptindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAPPLYDEPTINDEXNO() {
        return applydeptindexno;
    }

    /**
     * Sets the value of the applydeptindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAPPLYDEPTINDEXNO(String value) {
        this.applydeptindexno = value;
    }

    /**
     * Gets the value of the applydeptcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAPPLYDEPTCODE() {
        return applydeptcode;
    }

    /**
     * Sets the value of the applydeptcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAPPLYDEPTCODE(String value) {
        this.applydeptcode = value;
    }

    /**
     * Gets the value of the applydeptname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAPPLYDEPTNAME() {
        return applydeptname;
    }

    /**
     * Sets the value of the applydeptname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAPPLYDEPTNAME(String value) {
        this.applydeptname = value;
    }

    /**
     * Gets the value of the executdeptindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXECUTDEPTINDEXNO() {
        return executdeptindexno;
    }

    /**
     * Sets the value of the executdeptindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXECUTDEPTINDEXNO(String value) {
        this.executdeptindexno = value;
    }

    /**
     * Gets the value of the executdeptcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXECUTDEPTCODE() {
        return executdeptcode;
    }

    /**
     * Sets the value of the executdeptcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXECUTDEPTCODE(String value) {
        this.executdeptcode = value;
    }

    /**
     * Gets the value of the executdeptname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXECUTDEPTNAME() {
        return executdeptname;
    }

    /**
     * Sets the value of the executdeptname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXECUTDEPTNAME(String value) {
        this.executdeptname = value;
    }

    /**
     * Gets the value of the applydrindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAPPLYDRINDEXNO() {
        return applydrindexno;
    }

    /**
     * Sets the value of the applydrindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAPPLYDRINDEXNO(String value) {
        this.applydrindexno = value;
    }

    /**
     * Gets the value of the applydrcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAPPLYDRCODE() {
        return applydrcode;
    }

    /**
     * Sets the value of the applydrcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAPPLYDRCODE(String value) {
        this.applydrcode = value;
    }

    /**
     * Gets the value of the applydrname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAPPLYDRNAME() {
        return applydrname;
    }

    /**
     * Sets the value of the applydrname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAPPLYDRNAME(String value) {
        this.applydrname = value;
    }

    /**
     * Gets the value of the executdrindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXECUTDRINDEXNO() {
        return executdrindexno;
    }

    /**
     * Sets the value of the executdrindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXECUTDRINDEXNO(String value) {
        this.executdrindexno = value;
    }

    /**
     * Gets the value of the executdrcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXECUTDRCODE() {
        return executdrcode;
    }

    /**
     * Sets the value of the executdrcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXECUTDRCODE(String value) {
        this.executdrcode = value;
    }

    /**
     * Gets the value of the executdrname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEXECUTDRNAME() {
        return executdrname;
    }

    /**
     * Sets the value of the executdrname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEXECUTDRNAME(String value) {
        this.executdrname = value;
    }

    /**
     * Gets the value of the reportdrindexno property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getREPORTDRINDEXNO() {
        return reportdrindexno;
    }

    /**
     * Sets the value of the reportdrindexno property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setREPORTDRINDEXNO(String value) {
        this.reportdrindexno = value;
    }

    /**
     * Gets the value of the reportdrcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getREPORTDRCODE() {
        return reportdrcode;
    }

    /**
     * Sets the value of the reportdrcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setREPORTDRCODE(String value) {
        this.reportdrcode = value;
    }

    /**
     * Gets the value of the reportdrname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getREPORTDRNAME() {
        return reportdrname;
    }

    /**
     * Sets the value of the reportdrname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setREPORTDRNAME(String value) {
        this.reportdrname = value;
    }

    /**
     * Gets the value of the clinicdiagcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCLINICDIAGCODE() {
        return clinicdiagcode;
    }

    /**
     * Sets the value of the clinicdiagcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCLINICDIAGCODE(String value) {
        this.clinicdiagcode = value;
    }

    /**
     * Gets the value of the clinicdiagname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCLINICDIAGNAME() {
        return clinicdiagname;
    }

    /**
     * Sets the value of the clinicdiagname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCLINICDIAGNAME(String value) {
        this.clinicdiagname = value;
    }

    /**
     * Gets the value of the idnumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIDNUMBER() {
        return idnumber;
    }

    /**
     * Sets the value of the idnumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIDNUMBER(String value) {
        this.idnumber = value;
    }

    /**
     * Gets the value of the patname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPATNAME() {
        return patname;
    }

    /**
     * Sets the value of the patname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPATNAME(String value) {
        this.patname = value;
    }

    /**
     * Gets the value of the physisexcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPHYSISEXCODE() {
        return physisexcode;
    }

    /**
     * Sets the value of the physisexcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPHYSISEXCODE(String value) {
        this.physisexcode = value;
    }

    /**
     * Gets the value of the physisexname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPHYSISEXNAME() {
        return physisexname;
    }

    /**
     * Sets the value of the physisexname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPHYSISEXNAME(String value) {
        this.physisexname = value;
    }

    /**
     * Gets the value of the datebirth property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDATEBIRTH() {
        return datebirth;
    }

    /**
     * Sets the value of the datebirth property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDATEBIRTH(String value) {
        this.datebirth = value;
    }

    /**
     * Gets the value of the ethniccode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getETHNICCODE() {
        return ethniccode;
    }

    /**
     * Sets the value of the ethniccode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setETHNICCODE(String value) {
        this.ethniccode = value;
    }

    /**
     * Gets the value of the ethnicname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getETHNICNAME() {
        return ethnicname;
    }

    /**
     * Sets the value of the ethnicname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setETHNICNAME(String value) {
        this.ethnicname = value;
    }

    /**
     * Gets the value of the maritalstatuscode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMARITALSTATUSCODE() {
        return maritalstatuscode;
    }

    /**
     * Sets the value of the maritalstatuscode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMARITALSTATUSCODE(String value) {
        this.maritalstatuscode = value;
    }

    /**
     * Gets the value of the maritalstatusname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMARITALSTATUSNAME() {
        return maritalstatusname;
    }

    /**
     * Sets the value of the maritalstatusname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMARITALSTATUSNAME(String value) {
        this.maritalstatusname = value;
    }

    /**
     * Gets the value of the recorddate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRECORDDATE() {
        return recorddate;
    }

    /**
     * Sets the value of the recorddate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRECORDDATE(String value) {
        this.recorddate = value;
    }

    /**
     * Gets the value of the updatedate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUPDATEDATE() {
        return updatedate;
    }

    /**
     * Sets the value of the updatedate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUPDATEDATE(String value) {
        this.updatedate = value;
    }

    /**
     * Gets the value of the equipmentcode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEQUIPMENTCODE() {
        return equipmentcode;
    }

    /**
     * Sets the value of the equipmentcode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEQUIPMENTCODE(String value) {
        this.equipmentcode = value;
    }

    /**
     * Gets the value of the equipmentname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEQUIPMENTNAME() {
        return equipmentname;
    }

    /**
     * Sets the value of the equipmentname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEQUIPMENTNAME(String value) {
        this.equipmentname = value;
    }

    /**
     * Gets the value of the note property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNOTE() {
        return note;
    }

    /**
     * Sets the value of the note property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNOTE(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the action property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAction(String value) {
        this.action = value;
    }

}
