//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.12.11 at 05:04:36 PM CST
//


package com.zebone.nhis.ma.pub.platform.send.impl.yh.vo.CheckReport;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.zebone.nems.webservice.jingmei.vo.CheckReport package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PHYSISEXCODE_QNAME = new QName("", "PHYSI_SEX_CODE");
    private final static QName _EXECUTDEPTNAME_QNAME = new QName("", "EXECUT_DEPT_NAME");
    private final static QName _REPORTDRINDEXNO_QNAME = new QName("", "REPORT_DR_INDEX_NO");
    private final static QName _OUTHOSPINDEXNO_QNAME = new QName("", "OUTHOSP_INDEX_NO");
    private final static QName _REPORTDRCODE_QNAME = new QName("", "REPORT_DR_CODE");
    private final static QName _APPLYDRNAME_QNAME = new QName("", "APPLY_DR_NAME");
    private final static QName _MARITALSTATUSCODE_QNAME = new QName("", "MARITAL_STATUS_CODE");
    private final static QName _PHYSISEXNAME_QNAME = new QName("", "PHYSI_SEX_NAME");
    private final static QName _IDNUMBER_QNAME = new QName("", "ID_NUMBER");
    private final static QName _EXECUTDRINDEXNO_QNAME = new QName("", "EXECUT_DR_INDEX_NO");
    private final static QName _OPERPARTCODE_QNAME = new QName("", "OPER_PART_CODE");
    private final static QName _EQUIPMENTNAME_QNAME = new QName("", "EQUIPMENT_NAME");
    private final static QName _EXAMMETHODNAME_QNAME = new QName("", "EXAM_METHOD_NAME");
    private final static QName _VISITCARDNO_QNAME = new QName("", "VISIT_CARD_NO");
    private final static QName _EXECUTDRNAME_QNAME = new QName("", "EXECUT_DR_NAME");
    private final static QName _PATNAME_QNAME = new QName("", "PAT_NAME");
    private final static QName _NOTE_QNAME = new QName("", "NOTE");
    private final static QName _EXAMMETHODCODE_QNAME = new QName("", "EXAM_METHOD_CODE");
    private final static QName _INHOSPNUM_QNAME = new QName("", "INHOSP_NUM");
    private final static QName _OPERPARTNAME_QNAME = new QName("", "OPER_PART_NAME");
    private final static QName _PATINDEXNO_QNAME = new QName("", "PAT_INDEX_NO");
    private final static QName _APPLYDRINDEXNO_QNAME = new QName("", "APPLY_DR_INDEX_NO");
    private final static QName _DATEBIRTH_QNAME = new QName("", "DATE_BIRTH");
    private final static QName _EQUIPMENTCODE_QNAME = new QName("", "EQUIPMENT_CODE");
    private final static QName _EXECUTDATE_QNAME = new QName("", "EXECUT_DATE");
    private final static QName _REPORTNAME_QNAME = new QName("", "REPORT_NAME");
    private final static QName _UPDATEDATE_QNAME = new QName("", "UPDATE_DATE");
    private final static QName _EXECUTDRCODE_QNAME = new QName("", "EXECUT_DR_CODE");
    private final static QName _EXAMITEMCODE_QNAME = new QName("", "EXAM_ITEM_CODE");
    private final static QName _APPLYDATE_QNAME = new QName("", "APPLY_DATE");
    private final static QName _ETHNICNAME_QNAME = new QName("", "ETHNIC_NAME");
    private final static QName _ORDERGROUPNO_QNAME = new QName("", "ORDER_GROUP_NO");
    private final static QName _APPLYDRCODE_QNAME = new QName("", "APPLY_DR_CODE");
    private final static QName _EXAMPATRESOURCECODE_QNAME = new QName("", "EXAM_PAT_RESOURCE_CODE");
    private final static QName _EXAMCATEGNAME_QNAME = new QName("", "EXAM_CATEG_NAME");
    private final static QName _APPLYDEPTCODE_QNAME = new QName("", "APPLY_DEPT_CODE");
    private final static QName _APPLYDEPTNAME_QNAME = new QName("", "APPLY_DEPT_NAME");
    private final static QName _ELECTRREQUISITIONNO_QNAME = new QName("", "ELECTR_REQUISITION_NO");
    private final static QName _APPLYDEPTINDEXNO_QNAME = new QName("", "APPLY_DEPT_INDEX_NO");
    private final static QName _INHOSPNO_QNAME = new QName("", "INHOSP_NO");
    private final static QName _EXAMRESULT_QNAME = new QName("", "EXAM_RESULT");
    private final static QName _ETHNICCODE_QNAME = new QName("", "ETHNIC_CODE");
    private final static QName _REPORTNO_QNAME = new QName("", "REPORT_NO");
    private final static QName _ANAMNESISNO_QNAME = new QName("", "ANAMNESIS_NO");
    private final static QName _CLINICDIAGNAME_QNAME = new QName("", "CLINIC_DIAG_NAME");
    private final static QName _EXAMPATRESOURCENAME_QNAME = new QName("", "EXAM_PAT_RESOURCE_NAME");
    private final static QName _ORDERNO_QNAME = new QName("", "ORDER_NO");
    private final static QName _CLINICDIAGCODE_QNAME = new QName("", "CLINIC_DIAG_CODE");
    private final static QName _INHOSPINDEXNO_QNAME = new QName("", "INHOSP_INDEX_NO");
    private final static QName _MRNO_QNAME = new QName("", "MR_NO");
    private final static QName _REPORTDRNAME_QNAME = new QName("", "REPORT_DR_NAME");
    private final static QName _EXAMCATEGCODE_QNAME = new QName("", "EXAM_CATEG_CODE");
    private final static QName _OUTHOSPNO_QNAME = new QName("", "OUTHOSP_NO");
    private final static QName _EXAMDESCR_QNAME = new QName("", "EXAM_DESCR");
    private final static QName _MARITALSTATUSNAME_QNAME = new QName("", "MARITAL_STATUS_NAME");
    private final static QName _REPORTDATE_QNAME = new QName("", "REPORT_DATE");
    private final static QName _RECORDDATE_QNAME = new QName("", "RECORD_DATE");
    private final static QName _EXECUTDEPTCODE_QNAME = new QName("", "EXECUT_DEPT_CODE");
    private final static QName _EXAMITEMNAME_QNAME = new QName("", "EXAM_ITEM_NAME");
    private final static QName _EXECUTDEPTINDEXNO_QNAME = new QName("", "EXECUT_DEPT_INDEX_NO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zebone.nems.webservice.jingmei.vo.CheckReport
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckReportBody }
     *
     */
    public CheckReportBody createBody() {
        return new CheckReportBody();
    }

    /**
     * Create an instance of {@link CheckReportRow }
     *
     */
    public CheckReportRow createRow() {
        return new CheckReportRow();
    }

    /**
     * Create an instance of {@link CheckReportMsg }
     *
     */
    public CheckReportMsg createMsg() {
        return new CheckReportMsg();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PHYSI_SEX_CODE")
    public JAXBElement<String> createPHYSISEXCODE(String value) {
        return new JAXBElement<String>(_PHYSISEXCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXECUT_DEPT_NAME")
    public JAXBElement<String> createEXECUTDEPTNAME(String value) {
        return new JAXBElement<String>(_EXECUTDEPTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "REPORT_DR_INDEX_NO")
    public JAXBElement<String> createREPORTDRINDEXNO(String value) {
        return new JAXBElement<String>(_REPORTDRINDEXNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "OUTHOSP_INDEX_NO")
    public JAXBElement<String> createOUTHOSPINDEXNO(String value) {
        return new JAXBElement<String>(_OUTHOSPINDEXNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "REPORT_DR_CODE")
    public JAXBElement<String> createREPORTDRCODE(String value) {
        return new JAXBElement<String>(_REPORTDRCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "APPLY_DR_NAME")
    public JAXBElement<String> createAPPLYDRNAME(String value) {
        return new JAXBElement<String>(_APPLYDRNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MARITAL_STATUS_CODE")
    public JAXBElement<String> createMARITALSTATUSCODE(String value) {
        return new JAXBElement<String>(_MARITALSTATUSCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PHYSI_SEX_NAME")
    public JAXBElement<String> createPHYSISEXNAME(String value) {
        return new JAXBElement<String>(_PHYSISEXNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ID_NUMBER")
    public JAXBElement<String> createIDNUMBER(String value) {
        return new JAXBElement<String>(_IDNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXECUT_DR_INDEX_NO")
    public JAXBElement<String> createEXECUTDRINDEXNO(String value) {
        return new JAXBElement<String>(_EXECUTDRINDEXNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "OPER_PART_CODE")
    public JAXBElement<String> createOPERPARTCODE(String value) {
        return new JAXBElement<String>(_OPERPARTCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EQUIPMENT_NAME")
    public JAXBElement<String> createEQUIPMENTNAME(String value) {
        return new JAXBElement<String>(_EQUIPMENTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_METHOD_NAME")
    public JAXBElement<String> createEXAMMETHODNAME(String value) {
        return new JAXBElement<String>(_EXAMMETHODNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "VISIT_CARD_NO")
    public JAXBElement<String> createVISITCARDNO(String value) {
        return new JAXBElement<String>(_VISITCARDNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXECUT_DR_NAME")
    public JAXBElement<String> createEXECUTDRNAME(String value) {
        return new JAXBElement<String>(_EXECUTDRNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PAT_NAME")
    public JAXBElement<String> createPATNAME(String value) {
        return new JAXBElement<String>(_PATNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "NOTE")
    public JAXBElement<String> createNOTE(String value) {
        return new JAXBElement<String>(_NOTE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_METHOD_CODE")
    public JAXBElement<String> createEXAMMETHODCODE(String value) {
        return new JAXBElement<String>(_EXAMMETHODCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "INHOSP_NUM")
    public JAXBElement<String> createINHOSPNUM(String value) {
        return new JAXBElement<String>(_INHOSPNUM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "OPER_PART_NAME")
    public JAXBElement<String> createOPERPARTNAME(String value) {
        return new JAXBElement<String>(_OPERPARTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "PAT_INDEX_NO")
    public JAXBElement<String> createPATINDEXNO(String value) {
        return new JAXBElement<String>(_PATINDEXNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "APPLY_DR_INDEX_NO")
    public JAXBElement<String> createAPPLYDRINDEXNO(String value) {
        return new JAXBElement<String>(_APPLYDRINDEXNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "DATE_BIRTH")
    public JAXBElement<String> createDATEBIRTH(String value) {
        return new JAXBElement<String>(_DATEBIRTH_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EQUIPMENT_CODE")
    public JAXBElement<String> createEQUIPMENTCODE(String value) {
        return new JAXBElement<String>(_EQUIPMENTCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXECUT_DATE")
    public JAXBElement<String> createEXECUTDATE(String value) {
        return new JAXBElement<String>(_EXECUTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "REPORT_NAME")
    public JAXBElement<String> createREPORTNAME(String value) {
        return new JAXBElement<String>(_REPORTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "UPDATE_DATE")
    public JAXBElement<String> createUPDATEDATE(String value) {
        return new JAXBElement<String>(_UPDATEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXECUT_DR_CODE")
    public JAXBElement<String> createEXECUTDRCODE(String value) {
        return new JAXBElement<String>(_EXECUTDRCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_ITEM_CODE")
    public JAXBElement<String> createEXAMITEMCODE(String value) {
        return new JAXBElement<String>(_EXAMITEMCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "APPLY_DATE")
    public JAXBElement<String> createAPPLYDATE(String value) {
        return new JAXBElement<String>(_APPLYDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ETHNIC_NAME")
    public JAXBElement<String> createETHNICNAME(String value) {
        return new JAXBElement<String>(_ETHNICNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ORDER_GROUP_NO")
    public JAXBElement<String> createORDERGROUPNO(String value) {
        return new JAXBElement<String>(_ORDERGROUPNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "APPLY_DR_CODE")
    public JAXBElement<String> createAPPLYDRCODE(String value) {
        return new JAXBElement<String>(_APPLYDRCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_PAT_RESOURCE_CODE")
    public JAXBElement<String> createEXAMPATRESOURCECODE(String value) {
        return new JAXBElement<String>(_EXAMPATRESOURCECODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_CATEG_NAME")
    public JAXBElement<String> createEXAMCATEGNAME(String value) {
        return new JAXBElement<String>(_EXAMCATEGNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "APPLY_DEPT_CODE")
    public JAXBElement<String> createAPPLYDEPTCODE(String value) {
        return new JAXBElement<String>(_APPLYDEPTCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "APPLY_DEPT_NAME")
    public JAXBElement<String> createAPPLYDEPTNAME(String value) {
        return new JAXBElement<String>(_APPLYDEPTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ELECTR_REQUISITION_NO")
    public JAXBElement<String> createELECTRREQUISITIONNO(String value) {
        return new JAXBElement<String>(_ELECTRREQUISITIONNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "APPLY_DEPT_INDEX_NO")
    public JAXBElement<String> createAPPLYDEPTINDEXNO(String value) {
        return new JAXBElement<String>(_APPLYDEPTINDEXNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "INHOSP_NO")
    public JAXBElement<String> createINHOSPNO(String value) {
        return new JAXBElement<String>(_INHOSPNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_RESULT")
    public JAXBElement<String> createEXAMRESULT(String value) {
        return new JAXBElement<String>(_EXAMRESULT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ETHNIC_CODE")
    public JAXBElement<String> createETHNICCODE(String value) {
        return new JAXBElement<String>(_ETHNICCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "REPORT_NO")
    public JAXBElement<String> createREPORTNO(String value) {
        return new JAXBElement<String>(_REPORTNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ANAMNESIS_NO")
    public JAXBElement<String> createANAMNESISNO(String value) {
        return new JAXBElement<String>(_ANAMNESISNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "CLINIC_DIAG_NAME")
    public JAXBElement<String> createCLINICDIAGNAME(String value) {
        return new JAXBElement<String>(_CLINICDIAGNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_PAT_RESOURCE_NAME")
    public JAXBElement<String> createEXAMPATRESOURCENAME(String value) {
        return new JAXBElement<String>(_EXAMPATRESOURCENAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ORDER_NO")
    public JAXBElement<String> createORDERNO(String value) {
        return new JAXBElement<String>(_ORDERNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "CLINIC_DIAG_CODE")
    public JAXBElement<String> createCLINICDIAGCODE(String value) {
        return new JAXBElement<String>(_CLINICDIAGCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "INHOSP_INDEX_NO")
    public JAXBElement<String> createINHOSPINDEXNO(String value) {
        return new JAXBElement<String>(_INHOSPINDEXNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MR_NO")
    public JAXBElement<String> createMRNO(String value) {
        return new JAXBElement<String>(_MRNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "REPORT_DR_NAME")
    public JAXBElement<String> createREPORTDRNAME(String value) {
        return new JAXBElement<String>(_REPORTDRNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_CATEG_CODE")
    public JAXBElement<String> createEXAMCATEGCODE(String value) {
        return new JAXBElement<String>(_EXAMCATEGCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "OUTHOSP_NO")
    public JAXBElement<String> createOUTHOSPNO(String value) {
        return new JAXBElement<String>(_OUTHOSPNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_DESCR")
    public JAXBElement<String> createEXAMDESCR(String value) {
        return new JAXBElement<String>(_EXAMDESCR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MARITAL_STATUS_NAME")
    public JAXBElement<String> createMARITALSTATUSNAME(String value) {
        return new JAXBElement<String>(_MARITALSTATUSNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "REPORT_DATE")
    public JAXBElement<String> createREPORTDATE(String value) {
        return new JAXBElement<String>(_REPORTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "RECORD_DATE")
    public JAXBElement<String> createRECORDDATE(String value) {
        return new JAXBElement<String>(_RECORDDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXECUT_DEPT_CODE")
    public JAXBElement<String> createEXECUTDEPTCODE(String value) {
        return new JAXBElement<String>(_EXECUTDEPTCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXAM_ITEM_NAME")
    public JAXBElement<String> createEXAMITEMNAME(String value) {
        return new JAXBElement<String>(_EXAMITEMNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "EXECUT_DEPT_INDEX_NO")
    public JAXBElement<String> createEXECUTDEPTINDEXNO(String value) {
        return new JAXBElement<String>(_EXECUTDEPTINDEXNO_QNAME, String.class, null, value);
    }

}
