# webservice的服务配置，键：是发布的URL，值：ws接口的实现类。各项目按需增减，不用全部发布
ws:
  route:
    ZSBANHISWebService: com.zebone.nhis.webservice.cxf.impl.NHISZSBAWebServiceImpl
    ZSRMNHISWebService: com.zebone.nhis.webservice.cxf.impl.NHISZSRMWebServiceImpl
    SyxNHISWebService: com.zebone.nhis.webservice.cxf.impl.NHISGZWebServiceImpl
    PlatFormSyxWebService: com.zebone.nhis.webservice.syx.cxf.SyxPlatFormWebServiceImpl
    NHISLBselfWebService: com.zebone.nhis.webservice.cxf.impl.NHISLBselfWebServiceImpl
    SyxEmrWebService: com.zebone.nhis.webservice.syx.cxf.EmrSyxWebServiceImpl
    SyxScmHrWebService: com.zebone.nhis.webservice.syx.cxf.ScmHrWebServiceImpl
    NHISWeChatWebService: com.zebone.nhis.webservice.cxf.impl.NHISWeChatWebServiceImpl
    NHISWebService: com.zebone.nhis.webservice.cxf.impl.NHISWebServiceImpl
    NHISLBTmisWebService: com.zebone.nhis.webservice.cxf.impl.NHISLBTmisWebServiceImpl
    ShendaEmerWebService: com.zebone.nhis.webservice.sd.cxf.EmerWebServiceImpl
    NHISPSKQWebService: com.zebone.nhis.webservice.cxf.impl.NHISPSKQWebServiceImpl
    NHISPskqSchWebService: com.zebone.nhis.webservice.cxf.impl.NHISPskqSchWebServiceImpl
    NHISPskqHealthWebService: com.zebone.nhis.webservice.cxf.impl.NHISPskqHealthWebServiceImpl
    NHISTaiKangWebService: com.zebone.nhis.webservice.zhongshan.cxf.ZsbaTaiKangServiceImpl
    zsbaXrWebService: com.zebone.nhis.webservice.zhongshan.cxf.ZsbaXrWebServiceImpl
    NHISzsrmDrugPackService: com.zebone.nhis.webservice.zsrm.cxf.ZsrmDrugPackServiceImpl
    lbzySelfService: com.zebone.nhis.webservice.cxf.impl.NHISLbzySelfWebServiceImpl
    NHISPskqDataUpWebService: com.zebone.nhis.webservice.cxf.impl.NHISPskqDataUpWebServiceImpl

