//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.26 at 03:31:26 PM CST 
//


package com.zebone.nhis.webservice.vo.chagsetvo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}amount"/>
 *         &lt;element ref="{}amountAdd"/>
 *         &lt;element ref="{}amountHppi"/>
 *         &lt;element ref="{}amountPi"/>
 *         &lt;element ref="{}codeFreq"/>
 *         &lt;element ref="{}dateStart"/>
 *         &lt;element ref="{}days"/>
 *         &lt;element ref="{}dosage"/>
 *         &lt;element ref="{}euAdditem"/>
 *         &lt;element ref="{}euDrugtype"/>
 *         &lt;element ref="{}flagInsu"/>
 *         &lt;element ref="{}flagPv"/>
 *         &lt;element ref="{}itemcate"/>
 *         &lt;element ref="{}nameCg"/>
 *         &lt;element ref="{}nameDeptOrd"/>
 *         &lt;element ref="{}nameEmpInput"/>
 *         &lt;element ref="{}nameEmpOrd"/>
 *         &lt;element ref="{}nameSupply"/>
 *         &lt;element ref="{}nameUnitDos"/>
 *         &lt;element ref="{}ords"/>
 *         &lt;element ref="{}pkCgop"/>
 *         &lt;element ref="{}pkCnord"/>
 *         &lt;element ref="{}pkDeptEx"/>
 *         &lt;element ref="{}pkDeptOrd"/>
 *         &lt;element ref="{}pkDisc"/>
 *         &lt;element ref="{}pkEmpInput"/>
 *         &lt;element ref="{}pkEmpOrd"/>
 *         &lt;element ref="{}pkPi"/>
 *         &lt;element ref="{}pkPv"/>
 *         &lt;element ref="{}pkUnitDos"/>
 *         &lt;element ref="{}presNo"/>
 *         &lt;element ref="{}price"/>
 *         &lt;element ref="{}priceOrg"/>
 *         &lt;element ref="{}quan"/>
 *         &lt;element ref="{}ratioAdd"/>
 *         &lt;element ref="{}ratioDisc"/>
 *         &lt;element ref="{}ratioSelf"/>
 *         &lt;element ref="{}spec"/>
 *         &lt;element ref="{}ts"/>
 *         &lt;element ref="{}unit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amount",
    "amountAdd",
    "amountHppi",
    "amountPi",
    "codeFreq",
    "dateStart",
    "days",
    "dosage",
    "euAdditem",
    "euDrugtype",
    "flagInsu",
    "flagPv",
    "itemcate",
    "nameCg",
    "nameDeptOrd",
    "nameEmpInput",
    "nameEmpOrd",
    "nameSupply",
    "nameUnitDos",
    "ords",
    "pkCgop",
    "pkCnord",
    "pkDeptEx",
    "pkDeptOrd",
    "pkDisc",
    "pkEmpInput",
    "pkEmpOrd",
    "pkPi",
    "pkPv",
    "pkUnitDos",
    "presNo",
    "price",
    "priceOrg",
    "quan",
    "ratioAdd",
    "ratioDisc",
    "ratioSelf",
    "spec",
    "codeOrdType",
    "ts",
    "unit"
})
@XmlRootElement(name = "blOpDt")
public class BlOpDt {

    @XmlElement(required = true)
    protected Double amount;
    @XmlElement(required = true)
    protected Double amountAdd;
    @XmlElement(required = true)
    protected Double amountHppi;
    @XmlElement(required = true)
    protected Double amountPi;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codeFreq;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dateStart;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String days;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dosage;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String euAdditem;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String euDrugtype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String flagInsu;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String flagPv;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String itemcate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nameCg;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nameDeptOrd;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nameEmpInput;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nameEmpOrd;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nameSupply;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nameUnitDos;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ords;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkCgop;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkCnord;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkDeptEx;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkDeptOrd;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkDisc;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkEmpInput;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkEmpOrd;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkPi;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkPv;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkUnitDos;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String presNo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "NCName")
    protected Double price;
    @XmlElement(required = true)
    @XmlSchemaType(name = "NCName")
    protected Double priceOrg;
    @XmlElement(required = true)
    @XmlSchemaType(name = "NCName")
    protected Double quan;
    @XmlElement(required = true)
    @XmlSchemaType(name = "NCName")
    protected Double ratioAdd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "NCName")
    protected Double ratioDisc;
    @XmlElement(required = true)
    @XmlSchemaType(name = "NCName")
    protected Double ratioSelf;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String spec;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codeOrdType;
	@XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ts;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String unit;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(Double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the amountAdd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public Double getAmountAdd() {
        return amountAdd;
    }

    /**
     * Sets the value of the amountAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountAdd(Double value) {
        this.amountAdd = value;
    }

    /**
     * Gets the value of the amountHppi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public Double getAmountHppi() {
        return amountHppi;
    }

    /**
     * Sets the value of the amountHppi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountHppi(Double value) {
        this.amountHppi = value;
    }

    /**
     * Gets the value of the amountPi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public Double getAmountPi() {
        return amountPi;
    }

    /**
     * Sets the value of the amountPi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountPi(Double value) {
        this.amountPi = value;
    }
    
    /**
     * Sets the value of the codeOrdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
	public void setCodeOrdType(String codeOrdType) {
		this.codeOrdType = codeOrdType;
	}
    
    /**
     * Gets the value of the codeOrdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	public String getCodeOrdType() {
		return codeOrdType;
	}
	
	
    /**
     * Gets the value of the codeFreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeFreq() {
        return codeFreq;
    }
    /**
     * Sets the value of the codeFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeFreq(String value) {
        this.codeFreq = value;
    }
  
    /**
     * Gets the value of the dateStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateStart() {
        return dateStart;
    }

    /**
     * Sets the value of the dateStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateStart(String value) {
        this.dateStart = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDays(String value) {
        this.days = value;
    }

    /**
     * Gets the value of the dosage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * Sets the value of the dosage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDosage(String value) {
        this.dosage = value;
    }

    /**
     * Gets the value of the euAdditem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuAdditem() {
        return euAdditem;
    }

    /**
     * Sets the value of the euAdditem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuAdditem(String value) {
        this.euAdditem = value;
    }

    /**
     * Gets the value of the euDrugtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuDrugtype() {
        return euDrugtype;
    }

    /**
     * Sets the value of the euDrugtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuDrugtype(String value) {
        this.euDrugtype = value;
    }

    /**
     * Gets the value of the flagInsu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagInsu() {
        return flagInsu;
    }

    /**
     * Sets the value of the flagInsu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagInsu(String value) {
        this.flagInsu = value;
    }

    /**
     * Gets the value of the flagPv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagPv() {
        return flagPv;
    }

    /**
     * Sets the value of the flagPv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagPv(String value) {
        this.flagPv = value;
    }

    /**
     * Gets the value of the itemcate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemcate() {
        return itemcate;
    }

    /**
     * Sets the value of the itemcate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemcate(String value) {
        this.itemcate = value;
    }

    /**
     * Gets the value of the nameCg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameCg() {
        return nameCg;
    }

    /**
     * Sets the value of the nameCg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameCg(String value) {
        this.nameCg = value;
    }

    /**
     * Gets the value of the nameDeptOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameDeptOrd() {
        return nameDeptOrd;
    }

    /**
     * Sets the value of the nameDeptOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameDeptOrd(String value) {
        this.nameDeptOrd = value;
    }

    /**
     * Gets the value of the nameEmpInput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEmpInput() {
        return nameEmpInput;
    }

    /**
     * Sets the value of the nameEmpInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEmpInput(String value) {
        this.nameEmpInput = value;
    }

    /**
     * Gets the value of the nameEmpOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEmpOrd() {
        return nameEmpOrd;
    }

    /**
     * Sets the value of the nameEmpOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEmpOrd(String value) {
        this.nameEmpOrd = value;
    }

    /**
     * Gets the value of the nameSupply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSupply() {
        return nameSupply;
    }

    /**
     * Sets the value of the nameSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSupply(String value) {
        this.nameSupply = value;
    }

    /**
     * Gets the value of the nameUnitDos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameUnitDos() {
        return nameUnitDos;
    }

    /**
     * Sets the value of the nameUnitDos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameUnitDos(String value) {
        this.nameUnitDos = value;
    }

    /**
     * Gets the value of the ords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrds() {
        return ords;
    }

    /**
     * Sets the value of the ords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrds(String value) {
        this.ords = value;
    }

    /**
     * Gets the value of the pkCgop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkCgop() {
        return pkCgop;
    }

    /**
     * Sets the value of the pkCgop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkCgop(String value) {
        this.pkCgop = value;
    }

    /**
     * Gets the value of the pkCnord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkCnord() {
        return pkCnord;
    }

    /**
     * Sets the value of the pkCnord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkCnord(String value) {
        this.pkCnord = value;
    }

    /**
     * Gets the value of the pkDeptEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkDeptEx() {
        return pkDeptEx;
    }

    /**
     * Sets the value of the pkDeptEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkDeptEx(String value) {
        this.pkDeptEx = value;
    }

    /**
     * Gets the value of the pkDeptOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkDeptOrd() {
        return pkDeptOrd;
    }

    /**
     * Sets the value of the pkDeptOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkDeptOrd(String value) {
        this.pkDeptOrd = value;
    }

    /**
     * Gets the value of the pkDisc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkDisc() {
        return pkDisc;
    }

    /**
     * Sets the value of the pkDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkDisc(String value) {
        this.pkDisc = value;
    }

    /**
     * Gets the value of the pkEmpInput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkEmpInput() {
        return pkEmpInput;
    }

    /**
     * Sets the value of the pkEmpInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkEmpInput(String value) {
        this.pkEmpInput = value;
    }

    /**
     * Gets the value of the pkEmpOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkEmpOrd() {
        return pkEmpOrd;
    }

    /**
     * Sets the value of the pkEmpOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkEmpOrd(String value) {
        this.pkEmpOrd = value;
    }

    /**
     * Gets the value of the pkPi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkPi() {
        return pkPi;
    }

    /**
     * Sets the value of the pkPi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkPi(String value) {
        this.pkPi = value;
    }

    /**
     * Gets the value of the pkPv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkPv() {
        return pkPv;
    }

    /**
     * Sets the value of the pkPv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkPv(String value) {
        this.pkPv = value;
    }

    /**
     * Gets the value of the pkUnitDos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkUnitDos() {
        return pkUnitDos;
    }

    /**
     * Sets the value of the pkUnitDos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkUnitDos(String value) {
        this.pkUnitDos = value;
    }

    /**
     * Gets the value of the presNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresNo() {
        return presNo;
    }

    /**
     * Sets the value of the presNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresNo(String value) {
        this.presNo = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(Double value) {
        this.price = value;
    }

    /**
     * Gets the value of the priceOrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getPriceOrg() {
        return priceOrg;
    }

    /**
     * Sets the value of the priceOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceOrg(Double value) {
        this.priceOrg = value;
    }

    /**
     * Gets the value of the quan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getQuan() {
        return quan;
    }

    /**
     * Sets the value of the quan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuan(Double value) {
        this.quan = value;
    }

    /**
     * Gets the value of the ratioAdd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getRatioAdd() {
        return ratioAdd;
    }

    /**
     * Sets the value of the ratioAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatioAdd(Double value) {
        this.ratioAdd = value;
    }

    /**
     * Gets the value of the ratioDisc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getRatioDisc() {
        return ratioDisc;
    }

    /**
     * Sets the value of the ratioDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatioDisc(Double value) {
        this.ratioDisc = value;
    }

    /**
     * Gets the value of the ratioSelf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getRatioSelf() {
        return ratioSelf;
    }

    /**
     * Sets the value of the ratioSelf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatioSelf(Double value) {
        this.ratioSelf = value;
    }

    /**
     * Gets the value of the spec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpec() {
        return spec;
    }

    /**
     * Sets the value of the spec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpec(String value) {
        this.spec = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

}
