//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.26 at 03:31:26 PM CST 
//


package com.zebone.nhis.webservice.vo.chagsetvo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}aggregateAmount"/>
 *         &lt;element ref="{}amtInsuThird"/>
 *         &lt;element ref="{}blDeposits"/>
 *         &lt;element ref="{}blOpDts"/>
 *         &lt;element ref="{}codeEmpSt"/>
 *         &lt;element ref="{}medicarePayments"/>
 *         &lt;element ref="{}note"/>
 *         &lt;element ref="{}patientsPay"/>
 *         &lt;element ref="{}pkDeptSt"/>
 *         &lt;element ref="{}pkOrgSt"/>
 *         &lt;element ref="{}pkPi"/>
 *         &lt;element ref="{}pkPv"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aggregateAmount",
    "amtInsuThird",
    "blDeposits",
    "blOpDts",
    "codeEmpSt",
    "medicarePayments",
    "note",
    "patientsPay",
    "pkDeptSt",
    "pkOrgSt",
    "pkPi",
    "pkPv"
})
@XmlRootElement(name = "chagSett")
public class ChagSett {

    @XmlElement(required = true)
    protected BigDecimal aggregateAmount;
    @XmlElement(required = true)
    protected BigDecimal amtInsuThird;
    @XmlElement(required = true)
    protected BlDeposits blDeposits;
    @XmlElement(required = true)
    protected BlOpDts blOpDts;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String codeEmpSt;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String medicarePayments;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String note;
    @XmlElement(required = true)
    protected BigDecimal patientsPay;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkDeptSt;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkOrgSt;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkPi;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pkPv;

    /**
     * Gets the value of the aggregateAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAggregateAmount() {
        return aggregateAmount;
    }

    /**
     * Sets the value of the aggregateAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAggregateAmount(BigDecimal value) {
        this.aggregateAmount = value;
    }

    /**
     * Gets the value of the amtInsuThird property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmtInsuThird() {
        return amtInsuThird;
    }

    /**
     * Sets the value of the amtInsuThird property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmtInsuThird(BigDecimal value) {
        this.amtInsuThird = value;
    }

    /**
     * Gets the value of the blDeposits property.
     * 
     * @return
     *     possible object is
     *     {@link BlDeposits }
     *     
     */
    public BlDeposits getBlDeposits() {
        return blDeposits;
    }

    /**
     * Sets the value of the blDeposits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlDeposits }
     *     
     */
    public void setBlDeposits(BlDeposits value) {
        this.blDeposits = value;
    }

    /**
     * Gets the value of the blOpDts property.
     * 
     * @return
     *     possible object is
     *     {@link BlOpDts }
     *     
     */
    public BlOpDts getBlOpDts() {
        return blOpDts;
    }

    /**
     * Sets the value of the blOpDts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlOpDts }
     *     
     */
    public void setBlOpDts(BlOpDts value) {
        this.blOpDts = value;
    }

    /**
     * Gets the value of the codeEmpSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeEmpSt() {
        return codeEmpSt;
    }

    /**
     * Sets the value of the codeEmpSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeEmpSt(String value) {
        this.codeEmpSt = value;
    }

    /**
     * Gets the value of the medicarePayments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicarePayments() {
        return medicarePayments;
    }

    /**
     * Sets the value of the medicarePayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicarePayments(String value) {
        this.medicarePayments = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the patientsPay property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPatientsPay() {
        return patientsPay;
    }

    /**
     * Sets the value of the patientsPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPatientsPay(BigDecimal value) {
        this.patientsPay = value;
    }

    /**
     * Gets the value of the pkDeptSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkDeptSt() {
        return pkDeptSt;
    }

    /**
     * Sets the value of the pkDeptSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkDeptSt(String value) {
        this.pkDeptSt = value;
    }

    /**
     * Gets the value of the pkOrgSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkOrgSt() {
        return pkOrgSt;
    }

    /**
     * Sets the value of the pkOrgSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkOrgSt(String value) {
        this.pkOrgSt = value;
    }

    /**
     * Gets the value of the pkPi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkPi() {
        return pkPi;
    }

    /**
     * Sets the value of the pkPi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkPi(String value) {
        this.pkPi = value;
    }

    /**
     * Gets the value of the pkPv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkPv() {
        return pkPv;
    }

    /**
     * Sets the value of the pkPv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkPv(String value) {
        this.pkPv = value;
    }

}
