//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 05:10:19 PM CST 
//


package com.zebone.nhis.ma.pub.platform.send.impl.yh.vo.CnLabApplyAndOccDetail;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zebone.nems.webservice.jingmei.vo.CnLabApplyAndOccDetail package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class CnLabApplyAndOccDetailObjectFactory {

    private final static QName _TESTRESULTVALUE_QNAME = new QName("", "TEST_RESULT_VALUE");
    private final static QName _MIC_QNAME = new QName("", "MIC");
    private final static QName _SAMPLETYPECODE_QNAME = new QName("", "SAMPLE_TYPE_CODE");
    private final static QName _REFERENCERANGES_QNAME = new QName("", "REFERENCE_RANGES");
    private final static QName _UPDATEDATE_QNAME = new QName("", "UPDATE_DATE");
    private final static QName _BACTERIALCOLONYCOUNT_QNAME = new QName("", "BACTERIAL_COLONY_COUNT");
    private final static QName _TESTITEMCODE_QNAME = new QName("", "TEST_ITEM_CODE");
    private final static QName _TESTITEMNAME_QNAME = new QName("", "TEST_ITEM_NAME");
    private final static QName _NOTE_QNAME = new QName("", "NOTE");
    private final static QName _NORMALFLAG_QNAME = new QName("", "NORMAL_FLAG");
    private final static QName _SMEARRESULT_QNAME = new QName("", "SMEAR_RESULT");
    private final static QName _DIAMETER_QNAME = new QName("", "DIAMETER");
    private final static QName _TESTRESULTVALUEUNIT_QNAME = new QName("", "TEST_RESULT_VALUE_UNIT");
    private final static QName _INVALIDFLAG_QNAME = new QName("", "INVALID_FLAG");
    private final static QName _ELECTRREQUISITIONNO_QNAME = new QName("", "ELECTR_REQUISITION_NO");
    private final static QName _MICROBENAME_QNAME = new QName("", "MICROBE_NAME");
    private final static QName _RECORDDATE_QNAME = new QName("", "RECORD_DATE");
    private final static QName _SAMPLETYPENAME_QNAME = new QName("", "SAMPLE_TYPE_NAME");
    private final static QName _REPORTNO_QNAME = new QName("", "REPORT_NO");
    private final static QName _TESTDETAILITEMNAME_QNAME = new QName("", "TEST_DETAIL_ITEM_NAME");
    private final static QName _TESTDETAILITEMCODE_QNAME = new QName("", "TEST_DETAIL_ITEM_CODE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zebone.nems.webservice.jingmei.vo.CnLabApplyAndOccDetail
     * 
     */
    public CnLabApplyAndOccDetailObjectFactory() {
    }

    /**
     * Create an instance of {@link CnLabApplyAndOccDetailBody }
     * 
     */
    public CnLabApplyAndOccDetailBody createBody() {
        return new CnLabApplyAndOccDetailBody();
    }

    /**
     * Create an instance of {@link CnLabApplyAndOccDetailRow }
     * 
     */
    public CnLabApplyAndOccDetailRow createRow() {
        return new CnLabApplyAndOccDetailRow();
    }

    /**
     * Create an instance of {@link CnLabApplyAndOccDetailMsg }
     * 
     */
    public CnLabApplyAndOccDetailMsg createMsg() {
        return new CnLabApplyAndOccDetailMsg();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_RESULT_VALUE")
    public JAXBElement<String> createTESTRESULTVALUE(String value) {
        return new JAXBElement<String>(_TESTRESULTVALUE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIC")
    public JAXBElement<String> createMIC(String value) {
        return new JAXBElement<String>(_MIC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SAMPLE_TYPE_CODE")
    public JAXBElement<String> createSAMPLETYPECODE(String value) {
        return new JAXBElement<String>(_SAMPLETYPECODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REFERENCE_RANGES")
    public JAXBElement<String> createREFERENCERANGES(String value) {
        return new JAXBElement<String>(_REFERENCERANGES_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UPDATE_DATE")
    public JAXBElement<String> createUPDATEDATE(String value) {
        return new JAXBElement<String>(_UPDATEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BACTERIAL_COLONY_COUNT")
    public JAXBElement<String> createBACTERIALCOLONYCOUNT(String value) {
        return new JAXBElement<String>(_BACTERIALCOLONYCOUNT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_ITEM_CODE")
    public JAXBElement<String> createTESTITEMCODE(String value) {
        return new JAXBElement<String>(_TESTITEMCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_ITEM_NAME")
    public JAXBElement<String> createTESTITEMNAME(String value) {
        return new JAXBElement<String>(_TESTITEMNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NOTE")
    public JAXBElement<String> createNOTE(String value) {
        return new JAXBElement<String>(_NOTE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NORMAL_FLAG")
    public JAXBElement<String> createNORMALFLAG(String value) {
        return new JAXBElement<String>(_NORMALFLAG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SMEAR_RESULT")
    public JAXBElement<String> createSMEARRESULT(String value) {
        return new JAXBElement<String>(_SMEARRESULT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DIAMETER")
    public JAXBElement<String> createDIAMETER(String value) {
        return new JAXBElement<String>(_DIAMETER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_RESULT_VALUE_UNIT")
    public JAXBElement<String> createTESTRESULTVALUEUNIT(String value) {
        return new JAXBElement<String>(_TESTRESULTVALUEUNIT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INVALID_FLAG")
    public JAXBElement<String> createINVALIDFLAG(String value) {
        return new JAXBElement<String>(_INVALIDFLAG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ELECTR_REQUISITION_NO")
    public JAXBElement<String> createELECTRREQUISITIONNO(String value) {
        return new JAXBElement<String>(_ELECTRREQUISITIONNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MICROBE_NAME")
    public JAXBElement<String> createMICROBENAME(String value) {
        return new JAXBElement<String>(_MICROBENAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RECORD_DATE")
    public JAXBElement<String> createRECORDDATE(String value) {
        return new JAXBElement<String>(_RECORDDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SAMPLE_TYPE_NAME")
    public JAXBElement<String> createSAMPLETYPENAME(String value) {
        return new JAXBElement<String>(_SAMPLETYPENAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REPORT_NO")
    public JAXBElement<String> createREPORTNO(String value) {
        return new JAXBElement<String>(_REPORTNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "TEST_DETAIL_ITEM_CODE")
    public JAXBElement<String> createTESTDETAILITEMCODE(String value) {
        return new JAXBElement<String>(_TESTDETAILITEMCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "TEST_DETAIL_ITEM_NAME")
    public JAXBElement<String> createTESTDETAILITEMNAME(String value) {
        return new JAXBElement<String>(_TESTDETAILITEMNAME_QNAME, String.class, null, value);
    }

}
