//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.15 at 08:56:47 PM CST 
//


package com.zebone.nhis.webservice.vo.payordervo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nameDept"/>
 *         &lt;element ref="{}pkDept"/>
 *         &lt;element ref="{}codeIp"/>
 *         &lt;element ref="{}pkPv"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameDept",
    "pkDept",
    "codeIp",
    "pkPv"
})
@XmlRootElement(name = "depositData")
public class DepositData {

    @XmlElement(required = true)
    protected String nameDept;
    @XmlElement(required = true)
    protected String pkDept;
    @XmlElement(required = true)
    protected String codeIp;
    @XmlElement(required = true)
    protected String pkPv;

    /**
     * Gets the value of the nameDept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameDept() {
        return nameDept;
    }

    /**
     * Sets the value of the nameDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameDept(String value) {
        this.nameDept = value;
    }

    /**
     * Gets the value of the pkDept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkDept() {
        return pkDept;
    }

    /**
     * Sets the value of the pkDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkDept(String value) {
        this.pkDept = value;
    }

    /**
     * Gets the value of the codeIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeIp() {
        return codeIp;
    }

    /**
     * Sets the value of the codeIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeIp(String value) {
        this.codeIp = value;
    }

    /**
     * Gets the value of the pkPv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkPv() {
        return pkPv;
    }

    /**
     * Sets the value of the pkPv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkPv(String value) {
        this.pkPv = value;
    }

}
