//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.17 at 03:29:53 PM CST 
//


package com.zebone.nhis.webservice.vo.payordervo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}codeIp"/>
 *         &lt;element ref="{}pkPv"/>
 *         &lt;element ref="{}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codeIp",
    "pkPv",
    "dateTime"
})
@XmlRootElement(name = "inSettleData")
public class InSettleData {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String codeIp;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pkPv;
    @XmlElement(required = true)
    protected String dateTime;

    /**
     * Gets the value of the codeIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeIp() {
        return codeIp;
    }

    /**
     * Sets the value of the codeIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeIp(String value) {
        this.codeIp = value;
    }

    /**
     * Gets the value of the pkPv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkPv() {
        return pkPv;
    }

    /**
     * Sets the value of the pkPv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkPv(String value) {
        this.pkPv = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

}
