//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.15 at 08:56:47 PM CST 
//


package com.zebone.nhis.webservice.vo.payordervo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}regDatas"/>
 *         &lt;element ref="{}depositDatas"/>
 *         &lt;element ref="{}settleDatas"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "regDatas",
    "depositDatas",
    "settleDatas",
    "inSettleDatas"
})
@XmlRootElement(name = "orderData")
public class PayInfoOrderData {

    @XmlElement(required = true)
    protected RegDatas regDatas;
    @XmlElement(required = true)
    protected DepositDatas depositDatas;
	@XmlElement(required = true)
    protected SettleDatas settleDatas;
    @XmlElement(required = true)
    protected InSettleDatas inSettleDatas;

    public InSettleDatas getInSettleDatas() {
 		return inSettleDatas;
 	}

 	public void setInSettleDatas(InSettleDatas inSettleDatas) {
 		this.inSettleDatas = inSettleDatas;
 	}

    /**
     * Gets the value of the regDatas property.
     * 
     * @return
     *     possible object is
     *     {@link RegDatas }
     *     
     */
    public RegDatas getRegDatas() {
        return regDatas;
    }

    /**
     * Sets the value of the regDatas property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegDatas }
     *     
     */
    public void setRegDatas(RegDatas value) {
        this.regDatas = value;
    }

    /**
     * Gets the value of the depositDatas property.
     * 
     * @return
     *     possible object is
     *     {@link DepositDatas }
     *     
     */
    public DepositDatas getDepositDatas() {
        return depositDatas;
    }

    /**
     * Sets the value of the depositDatas property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositDatas }
     *     
     */
    public void setDepositDatas(DepositDatas value) {
        this.depositDatas = value;
    }

    /**
     * Gets the value of the settleDatas property.
     * 
     * @return
     *     possible object is
     *     {@link SettleDatas }
     *     
     */
    public SettleDatas getSettleDatas() {
        return settleDatas;
    }

    /**
     * Sets the value of the settleDatas property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettleDatas }
     *     
     */
    public void setSettleDatas(SettleDatas value) {
        this.settleDatas = value;
    }

}
