//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.15 at 08:56:47 PM CST 
//


package com.zebone.nhis.webservice.vo.payordervo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}amountPi"/>
 *         &lt;element ref="{}amountSt"/>
 *         &lt;element ref="{}dateSt"/>
 *         &lt;element ref="{}dtStype"/>
 *         &lt;element ref="{}nameDept"/>
 *         &lt;element ref="{}namePi"/>
 *         &lt;element ref="{}pkPv"/>
 *         &lt;element ref="{}pkSettle"/>
 *         &lt;element ref="{}codeSt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amountPi",
    "amountSt",
    "dateSt",
    "dtStype",
    "nameDept",
    "namePi",
    "pkPv",
    "pkSettle",
    "codeSt"
})
@XmlRootElement(name = "settleData")
public class SettleData {

    @XmlElement(required = true)
    protected String amountPi;
    @XmlElement(required = true)
    protected String amountSt;
    @XmlElement(required = true)
    protected String dateSt;
    @XmlElement(required = true)
    protected String dtStype;
    @XmlElement(required = true)
    protected String nameDept;
    @XmlElement(required = true)
    protected String namePi;
    @XmlElement(required = true)
    protected String pkPv;
    @XmlElement(required = true)
    protected String pkSettle;
    @XmlElement(required = true)
    protected String codeSt;

    /**
     * Gets the value of the amountPi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountPi() {
        return amountPi;
    }

    /**
     * Sets the value of the amountPi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountPi(String value) {
        this.amountPi = value;
    }

    /**
     * Gets the value of the amountSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountSt() {
        return amountSt;
    }

    /**
     * Sets the value of the amountSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountSt(String value) {
        this.amountSt = value;
    }

    /**
     * Gets the value of the dateSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateSt() {
        return dateSt;
    }

    /**
     * Sets the value of the dateSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateSt(String value) {
        this.dateSt = value;
    }

    /**
     * Gets the value of the dtStype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtStype() {
        return dtStype;
    }

    /**
     * Sets the value of the dtStype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtStype(String value) {
        this.dtStype = value;
    }

    /**
     * Gets the value of the nameDept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameDept() {
        return nameDept;
    }

    /**
     * Sets the value of the nameDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameDept(String value) {
        this.nameDept = value;
    }

    /**
     * Gets the value of the namePi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePi() {
        return namePi;
    }

    /**
     * Sets the value of the namePi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePi(String value) {
        this.namePi = value;
    }

    /**
     * Gets the value of the pkPv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkPv() {
        return pkPv;
    }

    /**
     * Sets the value of the pkPv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkPv(String value) {
        this.pkPv = value;
    }

    /**
     * Gets the value of the pkSettle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkSettle() {
        return pkSettle;
    }

    /**
     * Sets the value of the pkSettle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkSettle(String value) {
        this.pkSettle = value;
    }

    /**
     * Gets the value of the codeSt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSt() {
        return codeSt;
    }

    /**
     * Sets the value of the codeSt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSt(String value) {
        this.codeSt = value;
    }

}
