//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.11 at 04:51:20 PM CST 
//


package com.zebone.nhis.ma.pub.platform.send.impl.yh.vo.MessOuterResponse;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zebone.nems.webservice.jingmei.vo.OpRegInfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SourceSysCode_QNAME = new QName("", "SourceSysCode");
    private final static QName _TargetSysCode_QNAME = new QName("", "TargetSysCode");
    private final static QName _RetCon_QNAME = new QName("", "RetCon");
    private final static QName _RetCode_QNAME = new QName("", "RetCode");
    private final static QName _Fid_QNAME = new QName("", "Fid");
    private final static QName _Msg_QNAME = new QName("", "OpRegInfoMsg");
    private final static QName _CurrentPage_QNAME = new QName("", "currentPage");
    private final static QName _TotalPage_QNAME = new QName("", "totalPage");
    private final static QName _MsgDate_QNAME = new QName("", "MsgDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zebone.nems.webservice.jingmei.vo.OpRegInfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseRetInfo }
     * 
     */
    public ResponseRetInfo createRetInfo() {
        return new ResponseRetInfo();
    }

    /**
     * Create an instance of {@link ResponseOption }
     * 
     */
    public ResponseOption createResponseOption() {
        return new ResponseOption();
    }

    /**
     * Create an instance of {@link ResponseMsgInfo }
     * 
     */
    public ResponseMsgInfo createMsgInfo() {
        return new ResponseMsgInfo();
    }

    /**
     * Create an instance of {@link ResponseMessageHeader }
     * 
     */
    public ResponseMessageHeader createMessageHeader() {
        return new ResponseMessageHeader();
    }

    /**
     * Create an instance of {@link ResponseESBEntry }
     * 
     */
    public ResponseESBEntry createESBEntry() {
        return new ResponseESBEntry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SourceSysCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSourceSysCode(String value) {
        return new JAXBElement<String>(_SourceSysCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TargetSysCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTargetSysCode(String value) {
        return new JAXBElement<String>(_TargetSysCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RetCon")
    public JAXBElement<String> createRetCon(String value) {
        return new JAXBElement<String>(_RetCon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RetCode")
    public JAXBElement<String> createRetCode(String value) {
        return new JAXBElement<String>(_RetCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fid")
    public JAXBElement<String> createFid(String value) {
        return new JAXBElement<String>(_Fid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpRegInfoMsg")
    public JAXBElement<String> createMsg(String value) {
        return new JAXBElement<String>(_Msg_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "currentPage")
    public JAXBElement<BigInteger> createCurrentPage(BigInteger value) {
        return new JAXBElement<BigInteger>(_CurrentPage_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "totalPage")
    public JAXBElement<BigInteger> createTotalPage(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalPage_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgDate")
    public JAXBElement<String> createMsgDate(String value) {
        return new JAXBElement<String>(_MsgDate_QNAME, String.class, null, value);
    }

}
