package com.zebone.nhis.webservice.client.zhongshan.op;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.13
 * 2017-05-18T15:16:59.508+08:00
 * Generated source version: 3.0.13
 * 
 */
@WebService(targetNamespace = "http://www.medicalsystem.com.cn", name = "DocareTrunDataServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DocareTrunDataServiceSoap {

    /**
     * Docare医疗数据集成平台-更新病人住院信息数据
     */
    @WebResult(name = "UpdatePatsInHospitalResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "UpdatePatsInHospital", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdatePatsInHospital")
    @WebMethod(operationName = "UpdatePatsInHospital", action = "http://www.medicalsystem.com.cn/UpdatePatsInHospital")
    @ResponseWrapper(localName = "UpdatePatsInHospitalResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdatePatsInHospitalResponse")
    public java.lang.String updatePatsInHospital(
        @WebParam(name = "appClass", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String appClass,
        @WebParam(name = "from", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String from,
        @WebParam(name = "patMasterIndexXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String patMasterIndexXml
    );

    /**
     * Docare医疗数据集成平台-更新工作人员信息数据
     */
    @WebResult(name = "UpdateUsersResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "UpdateUsers", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdateUsers")
    @WebMethod(operationName = "UpdateUsers", action = "http://www.medicalsystem.com.cn/UpdateUsers")
    @ResponseWrapper(localName = "UpdateUsersResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdateUsersResponse")
    public java.lang.String updateUsers(
        @WebParam(name = "appClass", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String appClass,
        @WebParam(name = "from", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String from,
        @WebParam(name = "UsersXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String usersXml
    );

    /**
     * Docare医疗数据集成平台-获取术后登记记录
     */
    @WebResult(name = "GetOperationMasterAndPlanInfoResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "GetOperationMasterAndPlanInfo", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetOperationMasterAndPlanInfo")
    @WebMethod(operationName = "GetOperationMasterAndPlanInfo", action = "http://www.medicalsystem.com.cn/GetOperationMasterAndPlanInfo")
    @ResponseWrapper(localName = "GetOperationMasterAndPlanInfoResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetOperationMasterAndPlanInfoResponse")
    public java.lang.String getOperationMasterAndPlanInfo(
        @WebParam(name = "hisPatientId", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String hisPatientId,
        @WebParam(name = "hisVisitId", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String hisVisitId,
        @WebParam(name = "hisOperId", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String hisOperId
    );

    /**
     * Docare医疗数据集成平台-获取电子病历记录信息
     */
    @WebResult(name = "GetDataPatientEmrArchiveDetialInfoResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "GetDataPatientEmrArchiveDetialInfo", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetDataPatientEmrArchiveDetialInfo")
    @WebMethod(operationName = "GetDataPatientEmrArchiveDetialInfo", action = "http://www.medicalsystem.com.cn/GetDataPatientEmrArchiveDetialInfo")
    @ResponseWrapper(localName = "GetDataPatientEmrArchiveDetialInfoResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetDataPatientEmrArchiveDetialInfoResponse")
    public java.lang.String getDataPatientEmrArchiveDetialInfo(
        @WebParam(name = "appClass", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String appClass,
        @WebParam(name = "emrArchiveDetialXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String emrArchiveDetialXml
    );

    /**
     * Docare医疗数据集成平台开放对外接口函数
     */
    @WebResult(name = "SendInfoToDocareResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "SendInfoToDocare", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.SendInfoToDocare")
    @WebMethod(operationName = "SendInfoToDocare", action = "http://www.medicalsystem.com.cn/SendInfoToDocare")
    @ResponseWrapper(localName = "SendInfoToDocareResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.SendInfoToDocareResponse")
    public java.lang.String sendInfoToDocare(
        @WebParam(name = "from", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String from,
        @WebParam(name = "xml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String xml,
        @WebParam(name = "infoName", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String infoName
    );

    /**
     * Docare医疗数据集成平台-更新科室信息数据
     */
    @WebResult(name = "UpdateDeptDictResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "UpdateDeptDict", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdateDeptDict")
    @WebMethod(operationName = "UpdateDeptDict", action = "http://www.medicalsystem.com.cn/UpdateDeptDict")
    @ResponseWrapper(localName = "UpdateDeptDictResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdateDeptDictResponse")
    public java.lang.String updateDeptDict(
        @WebParam(name = "appClass", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String appClass,
        @WebParam(name = "from", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String from,
        @WebParam(name = "deptDictXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String deptDictXml
    );

    /**
     * Docare医疗数据集成平台-获取病人麻醉药品事件等相关信息
     */
    @WebResult(name = "GetAnesthesiaEventResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "GetAnesthesiaEvent", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetAnesthesiaEvent")
    @WebMethod(operationName = "GetAnesthesiaEvent", action = "http://www.medicalsystem.com.cn/GetAnesthesiaEvent")
    @ResponseWrapper(localName = "GetAnesthesiaEventResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetAnesthesiaEventResponse")
    public java.lang.String getAnesthesiaEvent(
        @WebParam(name = "operationScheduleXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String operationScheduleXml
    );

    /**
     * 提供上传文件列表
     */
    @WebResult(name = "OPOrigFileListResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "OPOrigFileList", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.OPOrigFileList")
    @WebMethod(operationName = "OPOrigFileList", action = "http://www.medicalsystem.com.cn/OPOrigFileList")
    @ResponseWrapper(localName = "OPOrigFileListResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.OPOrigFileListResponse")
    public java.lang.String opOrigFileList(
        @WebParam(name = "patient_id", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String patientId,
        @WebParam(name = "times", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String times,
        @WebParam(name = "visit_flag", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String visitFlag
    );

    /**
     * Docare医疗数据集成平台-更新手术预约信息数据-福建协和麻醉系统专用版本[信息交互]
     */
    @WebResult(name = "UpdateOperationScheduleResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "UpdateOperationSchedule", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdateOperationSchedule")
    @WebMethod(operationName = "UpdateOperationSchedule", action = "http://www.medicalsystem.com.cn/UpdateOperationSchedule")
    @ResponseWrapper(localName = "UpdateOperationScheduleResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdateOperationScheduleResponse")
    public java.lang.String updateOperationSchedule(
        @WebParam(name = "from", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String from,
        @WebParam(name = "operationScheduleXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String operationScheduleXml
    );

    /**
     * Docare医疗数据集成平台-更新病人基本信息数据
     */
    @WebResult(name = "UpdatePatMasterIndexResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "UpdatePatMasterIndex", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdatePatMasterIndex")
    @WebMethod(operationName = "UpdatePatMasterIndex", action = "http://www.medicalsystem.com.cn/UpdatePatMasterIndex")
    @ResponseWrapper(localName = "UpdatePatMasterIndexResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.UpdatePatMasterIndexResponse")
    public java.lang.String updatePatMasterIndex(
        @WebParam(name = "appClass", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String appClass,
        @WebParam(name = "from", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String from,
        @WebParam(name = "patMasterIndexXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String patMasterIndexXml
    );

    /**
     * Docare医疗数据集成平台-获取电子病历记录信息
     */
    @WebResult(name = "GetDataPatientEmrArchiveDetialResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "GetDataPatientEmrArchiveDetial", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetDataPatientEmrArchiveDetial")
    @WebMethod(operationName = "GetDataPatientEmrArchiveDetial", action = "http://www.medicalsystem.com.cn/GetDataPatientEmrArchiveDetial")
    @ResponseWrapper(localName = "GetDataPatientEmrArchiveDetialResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.GetDataPatientEmrArchiveDetialResponse")
    public java.lang.String getDataPatientEmrArchiveDetial(
        @WebParam(name = "appClass", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String appClass,
        @WebParam(name = "emrArchiveDetialXml", targetNamespace = "http://www.medicalsystem.com.cn")
        java.lang.String emrArchiveDetialXml
    );

    /**
     * Docare医疗数据集成平台-HelloWorld调试函数
     */
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.medicalsystem.com.cn")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://www.medicalsystem.com.cn/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.medicalsystem.com.cn", className = "com.zebone.nhis.webservice.client.op.HelloWorldResponse")
    public java.lang.String helloWorld();
}
